# Copyright 2026 The Fuchsia Authors
#
# Use of this source code is governed by a MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT

import("//build/cpp/library_headers.gni")
import("//zircon/kernel/kernel_rust_mod.gni")

library_headers("headers") {
  headers = [ "lib/mmu_rcu/simple_generational_rcu.h" ]
  public_deps = [
    # For <lib/arch/intrin.h>
    "//zircon/kernel/lib/arch",

    # For <ktl/atomic.h>
    "//zircon/kernel/lib/ktl",
  ]
}

kernel_rust_mod("mmu_rcu_rs") {
  sources = [ "src/mod.rs" ]
  deps = [ "//src/lib/zr" ]
  test_deps = [ "//zircon/kernel/lib/unittest:unittest-rs" ]
}

source_set("mmu_rcu") {
  public_deps = [ ":headers" ]
  deps = [ ":mmu_rcu_rs" ]
}

group("tests") {
  testonly = true
}

group("kernel-tests") {
  testonly = true
  deps = [ "tests" ]
}

group("phys-tests") {
  testonly = true
}

group("boot_tests") {
  testonly = true
}
