# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("//build/bazel/rules/rust:defs.bzl", "rustc_library")

package(default_applicable_licenses = ["//:license"])

rustc_library(
    name = "work-queue",
    srcs = [
        "src/lib.rs",
        "src/state.rs",
    ],
    crate_name = "work_queue",
    edition = "2024",
    lint_config = "//build/config/rust/lints:clippy_warn_all",
    test_deps = [
        "//src/lib/diagnostics/testing/diagnostics-assertions/rust:diagnostics-assertions",
        "//src/lib/fuchsia",
        "//src/lib/fuchsia-async",
    ],
    version = "0.1.0",
    visibility = ["//src/sys/pkg:__subpackages__"],
    with_unit_tests = True,
    deps = [
        "//src/lib/diagnostics/inspect/rust:fuchsia-inspect",
        "//src/lib/fuchsia-sync",
        "//third_party/rust_crates/vendor:anyhow",
        "//third_party/rust_crates/vendor:futures",
        "//third_party/rust_crates/vendor:pin-project",
        "//third_party/rust_crates/vendor:thiserror",
    ],
)
