# Copyright 2022 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/drivers.gni")

fuchsia_driver_dml("child-driver-dml") {
  dml = "meta/child-driver.dml"
  driver_name = "zircon_transport_child"
}

fuchsia_driver_dml("parent-driver-dml") {
  dml = "meta/parent-driver.dml"
  driver_name = "zircon_transport_parent"
}

driver_bind_rules("parent_bind") {
  dml_label = ":parent-driver-dml"
  bind_output = "parent-driver.bindbc"
  deps = [ "//src/devices/bind/fuchsia.test" ]
}

fuchsia_cc_driver("parent_driver") {
  legacy = true
  output_name = "zircon_transport_parent_v1"
  sources = [ "parent-driver.cc" ]
  deps = [
    ":parent_bind",
    "//examples/drivers/transport/zircon:fuchsia.examples.gizmo_cpp",
    "//sdk/lib/component/outgoing/cpp",
    "//sdk/lib/driver/runtime:driver_runtime_cpp",
    "//src/devices/lib/driver",
    "//src/devices/lib/driver:driver_runtime",
    "//src/lib/ddktl",
  ]
}

fuchsia_driver_component("parent_component") {
  dml_label = ":parent-driver-dml"
  deps = [ ":parent_driver" ]
  info = "meta/component-info.json"
}

driver_bind_rules("child_bind") {
  dml_label = ":child-driver-dml"
  bind_output = "child-driver.bindbc"
  deps = [ "//src/devices/bind/fuchsia" ]
}

fuchsia_cc_driver("child_driver") {
  legacy = true
  output_name = "zircon_transport_child_v1"
  sources = [ "child-driver.cc" ]
  deps = [
    ":child_bind",
    "//examples/drivers/transport/zircon:fuchsia.examples.gizmo_cpp",
    "//src/devices/lib/driver",
    "//src/lib/ddktl",
  ]
}

fuchsia_driver_component("child_component") {
  dml_label = ":child-driver-dml"
  deps = [ ":child_driver" ]
  info = "meta/component-info.json"
}
