# Copyright 2019 The Fuchsia Authors
#
# Use of this source code is governed by a MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT

import("//build/cpp/library_headers.gni")
import("//zircon/kernel/kernel_rust_mod.gni")

library_headers("headers") {
  headers = [ "lib/system-topology.h" ]
  public_deps = [
    # <lib/system-topology.h> has #include <ktl/span.h>.
    "//zircon/kernel/lib/ktl:headers",
  ]
}

kernel_rust_mod("topology_rs") {
  output_name = "topology"
  source_root = "src/mod.rs"
  sources = [
    "src/mod.rs",
    "src/tests.rs",
  ]
  deps = [
    "//sdk/rust/zbi",
    "//sdk/rust/zx-status",
    "//src/lib/kalloc",
    "//src/lib/kprint",
    "//src/lib/lazy_init:lazy_init_rs",
    "//src/lib/zr",
    "//third_party/rust_crates:zerocopy",
    "//zircon/kernel/lib/debug",
    "//zircon/system/ulib/fbl/rust:fbl",
  ]
  test_deps = [ "//zircon/kernel/lib/unittest:unittest-rs" ]
}

static_library("topology") {
  public_deps = [ ":headers" ]

  sources = [ "system-topology.cc" ]
  deps = [
    ":topology_rs",
    "//sdk/lib/zbi-format",
    "//zircon/kernel/lib/ktl",
    "//zircon/system/ulib/fbl",
  ]
}

group("tests") {
  testonly = true
}

source_set("kernel-tests") {
  testonly = true
  sources = [ "system-topology_test.cc" ]
  deps = [
    ".",
    "//zircon/kernel/lib/unittest",
  ]
}

group("phys-tests") {
  testonly = true
}

group("boot_tests") {
  testonly = true
}
