# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("//build/bazel/rules/cc:fx_cc_binary.bzl", "fx_cc_binary")
load(
    "//build/bazel/rules/cc:fx_packaged_binary.bzl",
    "fx_packaged_binary",
)
load(
    "//build/bazel/rules/components:fx_component.bzl",
    "fx_component",
    "fx_component_manifest",
)
load(
    "//build/bazel/rules/packages:fx_package.bzl",
    "fx_package",
)

package(default_applicable_licenses = ["//:license"])

exports_files(
    ["meta/build_info.core_shard.cml"],
    visibility = ["//bundles/assembly:__subpackages__"],
)

fx_cc_binary(
    name = "build_info",
    srcs = [
        "build_info.cc",
        "build_info.h",
        "main.cc",
    ],
    tags = ["manual"],
    deps = [
        "//sdk/fidl/fuchsia.buildinfo:fuchsia.buildinfo_cpp",
        "//sdk/lib/async-loop:async-loop-cpp",
        "//sdk/lib/async-loop:async-loop-default",
        "//sdk/lib/component/outgoing/cpp",
        "//sdk/lib/fdio",
        "//sdk/lib/syslog/cpp",
        "//src/lib/fsl",
    ],
)

fx_packaged_binary(
    name = "build_info_packaged_bin",
    binary = ":build_info",
    binary_name = "build_info",
)

fx_component_manifest(
    name = "build-info-manifest",
    component_name = "build-info",
    includes = [
        "//sdk/lib/syslog:client.shard.cml",
        "//sdk/lib/syslog:offer.shard.cml",
        "//sdk/lib/syslog:use.shard.cml",
    ],
    manifest = "meta/build_info.cml",
)

fx_component(
    name = "build-info-component",
    compiled_manifest = ":build-info-manifest",
    component_name = "build-info",
    visibility = [
        # TODO(https://fxbug.dev/490178129): Remove this visibility when build-info-service package
        # is added to the Bazel assembly.
        "//build/bazel/rules/tests:__subpackages__",
    ],
    deps = [
        ":build_info_packaged_bin",
    ],
)

fx_package(
    name = "build-info-service",
    package_name = "build-info-service",
    components = [
        ":build-info-component",
    ],
    visibility = [
        # TODO(https://fxbug.dev/490178129): Remove this visibility when build-info-service package
        # is added to the Bazel assembly.
        "//build/bazel/rules/tests:__subpackages__",
    ],
)
