# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("//build/bazel/rules/rust:defs.bzl", "rustc_library")

package(
    default_applicable_licenses = ["//:license"],
    default_visibility = ["//visibility:public"],
)

rustc_library(
    name = "virtgralloc",
    srcs = [
        "src/lib.rs",
        "src/virtgralloc.rs",
    ],
    crate_name = "virtgralloc",
    edition = "2024",
    lint_config = "//src/starnix/build:kernel_library_config",
    deps = [
        "//third_party/rust_crates/vendor:zerocopy",
    ],
)
