# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("//build/bazel/rules/rust:defs.bzl", "rustc_library")

package(default_applicable_licenses = ["//:license"])

rustc_library(
    name = "client",
    srcs = [
        "src/fidl_next.rs",
        "src/lib.rs",
    ],
    crate_name = "fuchsia_component_client",
    edition = "2024",
    target_compatible_with = ["@platforms//os:fuchsia"],
    test_deps = [
        "//src/lib/fuchsia-async",
        "//src/lib/fuchsia-component/tests:fuchsia.component.client.test_rust",
        "//src/storage/lib/vfs/rust:vfs",
        "//third_party/rust_crates/vendor:assert_matches",
    ],
    version = "0.1.0",
    visibility = ["//:__subpackages__"],
    with_unit_tests = True,
    deps = [
        "//sdk/fidl/fuchsia.component.decl:fuchsia.component.decl_rust",
        "//sdk/fidl/fuchsia.component:fuchsia.component_rust",
        "//sdk/fidl/fuchsia.io:fuchsia.io_rust",
        "//sdk/rust/zx",
        "//src/lib/fdio/rust:fdio",
        "//src/lib/fidl/rust/fidl",
        "//src/lib/fidl/rust_next/fidl_next",
        "//src/lib/fuchsia-component/directory",
        "//src/lib/fuchsia-fs",
        "//third_party/rust_crates/vendor:anyhow",
        "//third_party/rust_crates/vendor:futures",
        "//third_party/rust_crates/vendor:pin-project",
    ],
)
