# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/rust/rustc_library.gni")

rustc_library("ffx_profile_stacktrack_common") {
  edition = "2024"
  with_unit_tests = true

  deps = [
    "//sdk/fidl/fuchsia.developer.remotecontrol:fuchsia.developer.remotecontrol_rust_fdomain",
    "//sdk/fidl/fuchsia.memory.stacktrack.client:fuchsia.memory.stacktrack.client_rust_fdomain",
    "//sdk/fidl/fuchsia.sys2:fuchsia.sys2_rust_fdomain",
    "//src/developer/ffx/config:lib",
    "//src/developer/ffx/lib/errors:lib",
    "//src/developer/ffx/lib/rcs:lib",
    "//src/developer/ffx/lib/symbolize",
    "//src/lib/fdomain/client",
    "//src/performance/memory/stacktrack/lib/stacktrack_snapshot:stacktrack_snapshot_fdomain",
    "//src/sys/lib/cm_rust",
    "//src/sys/lib/component_debug:component_debug_fdomain",
    "//third_party/rust_crates:anyhow",
    "//third_party/rust_crates:itertools",
    "//third_party/rust_crates:schemars",
    "//third_party/rust_crates:serde",
  ]

  test_deps = [
    "//third_party/rust_crates:hex",
    "//third_party/rust_crates:serde_json",
  ]

  sources = [
    "src/lib.rs",
    "src/realm_query.rs",
    "src/resolved_snapshot.rs",
  ]
}
