# Copyright 2024 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//src/bringup/lib/restricted-machine/loadable.gni")

restricted_loadable_module("restricted-blob") {
  sources = [ "$current_cpu.S" ]
  deps = [ "//zircon/kernel/lib/arch" ]
}

# The boundary module is blob of code which will be mapped at the boundary of
# addressable memory.  For 64-bit targets, this is often impossible given other
# constraints, but for 32-bit targets, the 64-bit "host" will map this blob at a
# location which overlaps the boundary (0xffffffff).
#
# Once placed, different exception cases can be explored, such as invalid
# instruction prefetch when the next instruction if outside of the addressable
# memory.
restricted_loadable_module("boundary") {
  sources = [ "boundary.$current_cpu.S" ]
}

# The thumb module is a blob of code compiled in Thumb mode for ARM32.
# This tests that restricted mode can execute Thumb code and accept entry
# points with bit 0 set (the ARM Thumb interworking convention).
restricted_loadable_module("thumb") {
  sources = [ "thumb.$current_cpu.S" ]
  deps = [ "//zircon/kernel/lib/arch" ]
}
