# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("//build/bazel/rules/rust:defs.bzl", "rustc_library")

package(default_applicable_licenses = ["//:license"])

rustc_library(
    name = "context-authenticator",
    srcs = ["src/lib.rs"],
    crate_name = "context_authenticator",
    edition = "2024",
    lint_config = "//build/config/rust/lints:clippy_warn_all",
    test_deps = [
        "//src/lib/fuchsia",
        "//third_party/rust_crates/vendor:assert_matches",
    ],
    version = "0.1.0",
    visibility = [
        "//src/sys/component_manager:__subpackages__",
        "//src/sys/pkg:__subpackages__",
    ],
    with_unit_tests = True,
    deps = [
        "//sdk/fidl/fuchsia.pkg:fuchsia.pkg_rust",
        "//src/sys/pkg/lib/fuchsia-hash",
        "//third_party/rust_crates/vendor:hmac",
        "//third_party/rust_crates/vendor:rand",
        "//third_party/rust_crates/vendor:sha2",
        "//third_party/rust_crates/vendor:thiserror",
    ],
)
