# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("//build/bazel/rules/cc:fx_cc_library_headers.bzl", "fx_cc_library_headers")

package(default_applicable_licenses = ["//:license"])

fx_cc_library_headers(
    name = "asm_utils",
    hdrs = ["include/starnix_asm_utils/asm.h"],
    include_dir = "include",
    visibility = ["//visibility:public"],
)
