# Copyright 2019 The Fuchsia Authors
#
# Use of this source code is governed by a MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT

import("//build/components/fuchsia_unittest_package.gni")
import("//build/rust/rustc_binary.gni")
import("//build/test.gni")
import("//build/testing/boot_tests/boot_test.gni")

group("tests") {
  testonly = true
  deps = [ ":userboot-integration-tests" ]
}

fuchsia_unittest_package("userboot-integration-tests") {
  manifest = "meta/userboot_integration_tests.cml"
  deps = [ ":userboot-integration-tests-bin" ]
  test_type = "system"
}

test("userboot-integration-tests-bin") {
  sources = [ "integration_tests.cc" ]
  deps = [
    "//sdk/fidl/fuchsia.kernel:fuchsia.kernel_cpp",
    "//sdk/lib/component/incoming/cpp",
    "//sdk/lib/zbi-format:internal",
    "//src/bringup/lib/userboot/testing",
    "//src/lib/fxl/test:gtest_main",
    "//src/lib/zbitl",
    "//third_party/googletest:gmock",
    "//zircon/system/ulib/zx",
  ]
  data_deps = [
    ":userboot-rust.executable",
    ":userboot-test-rust.executable",
    "//src/bringup/lib/userboot:userboot-lib-static-pie-test",
  ]
}

template("rust_redirect") {
  group(target_name) {
    forward_variables_from(invoker,
                           [
                             "testonly",
                             "visibility",
                           ])
    if (current_toolchain ==
        "//build/toolchain/zircon:user.basic_${target_cpu}") {
      _helper_label = "${invoker.binary_label}($default_toolchain)"
      _helper_out_dir = get_label_info(_helper_label, "root_out_dir")
      deps = [ _helper_label ]
      metadata = {
        distribution_entries_barrier = []
        distribution_entries = [
          {
            source =
                rebase_path("$_helper_out_dir/${invoker.binary_output_name}",
                            root_build_dir)
            destination = invoker.install_name
            label = get_label_info(":$target_name", "label_with_toolchain")
          },
        ]
      }
    } else {
      public_deps =
          [ ":$target_name(//build/toolchain/zircon:user.basic_${target_cpu})" ]
      not_needed(invoker,
                 [
                   "binary_label",
                   "binary_output_name",
                   "install_name",
                 ])
    }
  }
}

rust_redirect("userboot") {
  binary_label = ":userboot-rust.executable"
  binary_output_name = "userboot_rust"
  install_name = "userboot"
}

rust_redirect("userboot-test-rust") {
  binary_label = ":userboot-test-rust.executable"
  binary_output_name = "userboot_test_rust"
  install_name = "userboot-test-rust"
}

static_remove_configs = [
  "//build/config/fuchsia:fdio_config",
  "//build/config/fuchsia:dynamic_rust_standard_library",
]

rustc_binary("userboot-rust.executable") {
  output_name = "userboot_rust"
  configs += static_remove_configs
  configs -= static_remove_configs

  edition = "2024"
  source_root = "main.rs"
  sources = [ source_root ]
  deps = [
    "//sdk/lib/c/stubs",
    "//src/bringup/lib/userboot/rust",
    "//src/bringup/lib/userboot/rust:bootfs",
    "//src/bringup/lib/userboot/rust:cmdline",
    "//src/bringup/lib/userboot/rust:program",
    "//src/firmware/lib/zbi-rs",
    "//src/lib/fuchsia-async",
    "//src/lib/fuchsia-runtime",
    "//third_party/rust_crates:anyhow",
    "//third_party/rust_crates:zerocopy",
  ]

  exclude_toolchain_tags = [
    "uses-shadow",
    "uses-shlibs",
  ]
}

rustc_binary("userboot-test-rust.executable") {
  output_name = "userboot_test_rust"
  configs += static_remove_configs
  configs -= static_remove_configs

  rustenv = [ "BOOT_TEST_SUCCESS_STRING=$boot_test_success_string" ]

  edition = "2024"
  source_root = "test_main.rs"
  sources = [ source_root ]
  deps = [
    "//sdk/fidl/fuchsia.boot:fuchsia.boot_rust_next",
    "//sdk/fidl/fuchsia.io:fuchsia.io_rust_next",
    "//sdk/lib/c/stubs",
    "//sdk/rust/zx",
    "//src/bringup/lib/userboot/rust",
    "//src/bringup/lib/userboot/rust:bootfs",
    "//src/bringup/lib/userboot/rust:cmdline",
    "//src/bringup/lib/userboot/rust:program",
    "//src/firmware/lib/zbi-rs",
    "//src/lib/fidl/rust_next/fidl_next",
    "//src/lib/fuchsia-async",
    "//src/lib/fuchsia-runtime",
    "//src/lib/process_builder",
    "//third_party/rust_crates:anyhow",
    "//third_party/rust_crates:zerocopy",
  ]

  exclude_toolchain_tags = [ "uses-shadow" ]
}
