# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("../libc.gni")

llvm_libc_source_set("wctype") {
  functions = [
    "iswalnum",
    "iswalpha",
    "iswblank",
    "iswcntrl",
    "iswctype",
    "iswdigit",
    "iswgraph",
    "iswlower",
    "iswprint",
    "iswpunct",
    "iswspace",
    "iswupper",
    "iswxdigit",
    "towlower",
    "towupper",
  ]

  # The llvm-libc header has a nonstandard name for reasons that don't apply
  # here, so include-preempt provides a wrapper.
  preempt_header_functions = [ "wctype" ]
  functions += preempt_header_functions

  deps = [ ":support" ]
}

llvm_libc_source_set("support") {
  dir = "__support/wctype"

  # This doesn't define any functions with tests of their own, but it's still
  # an llvm_libc_source_set() to get the dual production and testonly targets.
  # (There will also be an unused empty unittests subtarget.)
  functions = []

  public = [
    "lower_to_upper.h",
    "perfect_hash_map.h",
    "wctype_classification_utils.h",
    "wctype_conversion_utils.h",
  ]

  sources = [
    "wctype_classification_utils.cpp",
    "wctype_conversion_utils.cpp",
  ]
}
