# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("//build/bazel/rules/fidl:fidl_library.bzl", "fidl_library")
load("//build/bazel/rules/rust:defs.bzl", "rustc_library")

package(default_applicable_licenses = ["//:license"])

_COMMON_SRCS = [
    "src/directory.rs",
    "src/directory/watcher.rs",
    "src/file.rs",
    "src/file/async_read_at.rs",
    "src/file/async_read_at_ext.rs",
    "src/file/async_reader.rs",
    "src/file/buffered_async_read_at.rs",
    "src/lib.rs",
    "src/node.rs",
]

# @bazel2gn:transformer=deps
_COMMON_DEPS = [
    "//sdk/rust/zx-status",
    "//sdk/rust/zx-status-ext",
    "//src/lib/fidl/rust/fidl",
    "//src/lib/fuchsia-async",
    "//third_party/rust_crates/vendor:futures",
    "//third_party/rust_crates/vendor:pin-project",
    "//third_party/rust_crates/vendor:rand",
    "//third_party/rust_crates/vendor:static_assertions",
    "//third_party/rust_crates/vendor:thiserror",
    "//third_party/rust_crates/vendor:zerocopy",
]

# @bazel2gn:transformer=deps
_COMMON_TEST_DEPS = [
    ":fidl.test.schema_rust",
    "//src/lib/fuchsia",
    "//src/storage/lib/vfs/rust:vfs",
    "//third_party/rust_crates/vendor:assert_matches",
    "//third_party/rust_crates/vendor:proptest",
    "//third_party/rust_crates/vendor:tempfile",
]

rustc_library(
    name = "fuchsia-fs",
    srcs = _COMMON_SRCS,
    crate_name = "fuchsia_fs",
    edition = "2024",
    test_deps = _COMMON_TEST_DEPS,
    visibility = ["//:__subpackages__"],
    with_unit_tests = True,
    deps = _COMMON_DEPS + [
        "//sdk/fidl/fuchsia.io:fuchsia.io_rust_flex",
        "//src/lib/fdomain/client:flex_fidl",
    ] + select({
        "@platforms//os:fuchsia": [
            "//sdk/rust/zx",
            "//src/lib/fdio/rust:fdio",
        ],
        "//conditions:default": [],
    }),
)

rustc_library(
    name = "fuchsia-fs_fdomain",
    srcs = _COMMON_SRCS,
    crate_features = ["fdomain"],
    crate_name = "fuchsia_fs_fdomain",
    edition = "2024",
    test_deps = _COMMON_TEST_DEPS,
    visibility = ["//:__subpackages__"],
    with_unit_tests = True,
    deps = _COMMON_DEPS + [
        "//sdk/fidl/fuchsia.io:fuchsia.io_rust_fdomain_flex",
        "//src/lib/fdomain/client:flex_fdomain",
    ],
)

fidl_library(
    name = "fidl.test.schema",
    testonly = True,
    srcs = ["data/schema.test.fidl"],
)
