# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("//build/bazel/rules/rust:defs.bzl", "rustc_library")

package(default_applicable_licenses = ["//:license"])

rustc_library(
    name = "rust",
    srcs = ["src/lib.rs"],
    crate_name = "fuchsia_scheduler",
    edition = "2024",
    target_compatible_with = ["@platforms//os:fuchsia"],
    visibility = ["//:__subpackages__"],
    deps = [
        "//sdk/fidl/fuchsia.scheduler:fuchsia.scheduler_rust",
        "//sdk/rust/zx",
        "//src/lib/fuchsia-component/client",
        "//src/lib/fuchsia-runtime",
        "//src/lib/fuchsia-sync",
        "//third_party/rust_crates/vendor:anyhow",
    ],
)
