# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("@platforms//host:constraints.bzl", "HOST_CONSTRAINTS")
load("//build/bazel/rules/rust:defs.bzl", "rustc_library")

package(default_applicable_licenses = ["//:license"])

rustc_library(
    name = "lib",
    srcs = ["src/lib.rs"],
    crate_name = "fastboot_file_discovery",
    edition = "2024",
    target_compatible_with = HOST_CONSTRAINTS,
    test_deps = [
        "//src/lib/fuchsia",
        "//third_party/rust_crates/vendor:pretty_assertions",
        "//third_party/rust_crates/vendor:tempfile",
    ],
    visibility = [
        ":__pkg__",
        "//src/developer/ffx/lib/diagnostics/checks:__pkg__",
        "//src/developer/ffx/lib/discovery:__pkg__",
        "//src/developer/ffx/lib/fastboot:__pkg__",
        "//src/developer/ffx/lib/fastboot/connection_factory:__pkg__",
        "//src/developer/ffx/lib/target:__pkg__",
        "//src/developer/ffx/plugins/target/bootloader:__pkg__",
        "//src/developer/ffx/plugins/target/fastboot:__pkg__",
        "//src/developer/ffx/plugins/target/flash:__pkg__",
        "//vendor:__subpackages__",
    ],
    with_host_unit_tests = True,
    deps = [
        "//src/lib/fuchsia-async",
        "//third_party/rust_crates/vendor:futures",
        "//third_party/rust_crates/vendor:log",
        "//third_party/rust_crates/vendor:notify",
        "//third_party/rust_crates/vendor:thiserror",
    ],
)
