# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("//build/bazel/rules/rust:defs.bzl", "rustc_library")

package(default_applicable_licenses = ["//:license"])

rustc_library(
    name = "directory",
    srcs = ["src/lib.rs"],
    crate_name = "fuchsia_component_directory",
    edition = "2024",
    target_compatible_with = ["@platforms//os:fuchsia"],
    test_deps = [
        "//src/lib/fuchsia-async",
        "//src/lib/fuchsia-fs",
        "//src/storage/lib/vfs/rust:vfs",
        "//third_party/rust_crates/vendor:assert_matches",
    ],
    visibility = ["//:__subpackages__"],
    with_unit_tests = True,
    deps = [
        "//sdk/fidl/fuchsia.io:fuchsia.io_rust",
        "//sdk/rust/zx",
        "//src/lib/fidl/rust/fidl",
        "//third_party/rust_crates/vendor:anyhow",
    ],
)
