# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# LINT.IfChange

config("macaddr_config") {
  include_dirs = [ "include" ]
}

source_set("macaddr") {
  sources = [
    "include/wlan/drivers/macaddr.h",
    "macaddr.cc",
  ]
  public_configs = [ ":macaddr_config" ]
}
# LINT.ThenChange(BUILD.bazel)
