# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/fidl/fidl.gni")
import("//build/rust/rustc_library.gni")

fidl("fuchsia.board.dml.config") {
  sources = [ "fidl/config.fidl" ]
  public_deps = [ "//sdk/fidl/fuchsia.driver.metadata" ]
}

rustc_library("dml-config") {
  edition = "2024"
  name = "dml_config"
  source_root = "src/lib.rs"
  sources = [
    "src/lib.rs",
    "src/parser.rs",
  ]
  deps = [
    ":fuchsia.board.dml.config_rust",
    "//sdk/fidl/fuchsia.driver.metadata:fuchsia.driver.metadata_rust",
  ]
  if (is_fuchsia) {
    deps += [
      "//sdk/fidl/fuchsia.driver.framework:fuchsia.driver.framework_rust_next",
      "//sdk/fidl/fuchsia.hardware.platform.bus:fuchsia.hardware.platform.bus_rust_next",
      "//sdk/lib/driver/runtime/rust/fidl",
      "//sdk/rust/zx",
      "//src/lib/fidl/rust_next/fidl_next",
      "//third_party/rust_crates:anyhow",
      "//third_party/rust_crates:log",
      "//third_party/rust_crates:phf",
    ]
  }
}
