# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# TODO(https://fxbug.dev/533568124): Delete once dependents have been moved
# over to depending on //src/devices/testing/driver-unit-test.
group("driver-unit-test") {
  public_deps = [ "//src/devices/testing/driver-unit-test" ]
}
