# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/components.gni")
import("//build/test.gni")
import("//build/testing/environments.gni")

test("generic-board-test-bin") {
  sources = [ "generic-board-test.cc" ]
  deps = [
    "//sdk/fidl/fuchsia.driver.test:fuchsia.driver.test_cpp",
    "//sdk/lib/async-loop:async-loop-cpp",
    "//sdk/lib/async-loop:async-loop-default",
    "//sdk/lib/device-watcher/cpp",
    "//sdk/lib/driver_test_realm/realm_builder/cpp",
    "//src/lib/fxl/test:gtest_main",
    "//zircon/system/ulib/sync",
  ]
}

fuchsia_component("generic-board-test-component") {
  testonly = true
  component_name = "generic-board-test"
  manifest = "meta/generic-board-test.cml"
  deps = [ ":generic-board-test-bin" ]
}

fuchsia_test_package("generic-board-test-package") {
  package_name = "generic-board-test"
  test_components = [ ":generic-board-test-component" ]
  test_specs = {
    environments = [
      emu_env,
      vim3_env,
    ]
  }
  deps = [
    "//sdk/lib/driver_test_realm:driver_manager_test",
    "//sdk/lib/driver_test_realm:driver_test_realm_component",
    "//sdk/lib/driver_test_realm:manifest_provider",
    "//src/devices/bus/drivers/platform:platform-bus",
    "//src/devices/tests/generic-board:board-config",
    "//src/devices/tests/generic-board:generic-board-component",
    "//src/devices/tests/generic-board/fake-clock:fake-clock-component",
    "//src/devices/tests/generic-board/fake-device:fake-device-component",
    "//src/lib/fuchsia-component-test/realm_builder_server:realm_builder_server_component",
  ]
}
