# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

action("gen_null_vulkan_source") {
  visibility = [ ":*" ]
  script = "gen_null_vulkan.py"
  inputs = [ "//third_party/Vulkan-Headers/src/registry/vk.xml" ]
  outputs = [ "$target_gen_dir/null_vulkan.cc" ]
  args = [
    "--vk-xml",
    rebase_path("//third_party/Vulkan-Headers/src/registry/vk.xml",
                root_build_dir),
    "--output",
    rebase_path("$target_gen_dir/null_vulkan.cc", root_build_dir),
  ]
}

source_set("null_vulkan") {
  sources = get_target_outputs(":gen_null_vulkan_source")
  deps = [
    ":gen_null_vulkan_source",
    "//src/lib/vulkan:headers",
  ]
}
