# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("//build/bazel/rules/rust:defs.bzl", "rustc_library")

package(default_applicable_licenses = ["//:license"])

rustc_library(
    name = "mock-paver",
    srcs = ["src/lib.rs"],
    crate_name = "mock_paver",
    edition = "2024",
    lint_config = "//build/config/rust/lints:clippy_warn_all",
    proc_macro_deps = [
        "//third_party/rust_crates/vendor:async-trait",
    ],
    test_deps = [
        "//src/lib/fuchsia",
        "//third_party/rust_crates/vendor:assert_matches",
    ],
    version = "0.1.0",
    visibility = [
        "//src/security:__subpackages__",
        "//src/sys/pkg:__subpackages__",
        "//vendor/google/starnix:__subpackages__",
    ],
    with_unit_tests = True,
    deps = [
        "//sdk/fidl/fuchsia.mem:fuchsia.mem_rust",
        "//sdk/fidl/fuchsia.paver:fuchsia.paver_rust",
        "//sdk/rust/zx",
        "//src/lib/fidl/rust/fidl",
        "//src/lib/fuchsia-async",
        "//src/lib/fuchsia-sync",
        "//third_party/rust_crates/vendor:anyhow",
        "//third_party/rust_crates/vendor:futures",
    ],
)
