# Copyright 2019 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("buffer") {
  public = [
    "array_buffer.h",
    "block_buffer.h",
    "block_buffer_view.h",
    "blocking_ring_buffer.h",
    "ring_buffer.h",
  ]
  sources = [
    "array_buffer.cc",
    "block_buffer.cc",
  ]
  public_deps = [ "//sdk/fidl/fuchsia.storage.block:fuchsia.storage.block_cpp" ]
  deps = [ "//zircon/third_party/ulib/safemath" ]

  if (is_fuchsia) {
    public += [
      "mapped_vmo.h",
      "owned_vmoid.h",
      "resizeable_vmo_buffer.h",
      "vmo_bitmap_storage.h",
      "vmo_buffer.h",
      "vmoid_registry.h",
    ]
    sources += [
      "blocking_ring_buffer.cc",
      "mapped_vmo.cc",
      "owned_vmoid.cc",
      "resizeable_vmo_buffer.cc",
      "ring_buffer.cc",
      "vmo_buffer.cc",
    ]
    public_deps += [
      "//src/storage/lib/operation",
      "//zircon/system/ulib/fzl",
      "//zircon/system/ulib/zx",
    ]
    deps += [ "//sdk/lib/fdio" ]
  }
}

group("tests") {
  testonly = true
  deps = [ "test:tests" ]
}
