# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(
    default_applicable_licenses = ["//:license"],
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "buffer",
    srcs = [
        "array_buffer.cc",
        "block_buffer.cc",
        "blocking_ring_buffer.cc",
        "mapped_vmo.cc",
        "owned_vmoid.cc",
        "resizeable_vmo_buffer.cc",
        "ring_buffer.cc",
        "vmo_buffer.cc",
    ],
    hdrs = [
        "array_buffer.h",
        "block_buffer.h",
        "block_buffer_view.h",
        "blocking_ring_buffer.h",
        "mapped_vmo.h",
        "owned_vmoid.h",
        "resizeable_vmo_buffer.h",
        "ring_buffer.h",
        "vmo_bitmap_storage.h",
        "vmo_buffer.h",
        "vmoid_registry.h",
    ],
    target_compatible_with = ["@platforms//os:fuchsia"],
    deps = [
        "//src/storage/lib/operation",
        "//zircon/system/ulib/fzl",
        "//zircon/third_party/ulib/safemath",
        "@fuchsia_sdk//fidl/fuchsia.storage.block:fuchsia.storage.block_cpp",
        "@fuchsia_sdk//pkg/fdio",
        "@fuchsia_sdk//pkg/zx",
    ],
)
