# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("//build/tools/json_merge:json_merge.bzl", "json_merge")

package(
    default_applicable_licenses = ["//:license"],
    default_visibility = ["//visibility:public"],
)

exports_files([
    "data/config.json",
    "lib/pbms/data/config.json",
])

# TODO(https://fxbug.dev/512659653): Match the target in GN to include configs for more plugins and
# subtools.
json_merge(
    name = "ffx-defaults.json",
    srcs = [
        "data/config.json",
        "lib/pbms/data/config.json",
    ],
    deep_merge = True,
)

test_suite(
    name = "tests",
    tests = [
        "//src/developer/ffx/lib/arg_parsing:lib_test",
        "//src/developer/ffx/lib/buildid:lib_test",
        "//src/developer/ffx/lib/compat_info:lib_test",
        "//src/developer/ffx/lib/daemonize:lib_test",
        "//src/developer/ffx/lib/errors:lib_test",
        "//src/developer/ffx/lib/logging:lib_test",
        "//src/developer/ffx/lib/metrics:lib_test",
        "//src/developer/ffx/lib/netext:lib_test",
        "//src/developer/ffx/lib/port_picker:lib_test",
        "//src/developer/ffx/lib/safe_string:lib_test",
        "//src/developer/ffx/lib/target_errors:lib_test",
        "//src/developer/ffx/lib/termio:termio_test",
        "//src/developer/ffx/lib/traceable_error:lib_test",
        "//src/developer/ffx/lib/version:lib_test",
    ],
)
