// Copyright 2026 The Fuchsia Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

use anyhow::Context;
use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::collections::{HashMap, HashSet};
use std::fs::File;
use std::path::{Path, PathBuf};

pub use crate::property_def::*;

#[derive(Deserialize, Debug, Clone, PartialEq, Default)]
pub struct PciBind {
    pub vid: Option<Value>,
    pub did: Option<Value>,
    pub class: Option<Value>,
    pub subclass: Option<Value>,
    pub interface: Option<Value>,
    pub revision: Option<Value>,
    pub topo: Option<Value>,
}

#[derive(Deserialize, Debug, Clone, PartialEq, Default)]
pub struct UsbBind {
    pub vid: Option<Value>,
    pub pid: Option<Value>,
    pub class: Option<Value>,
    pub subclass: Option<Value>,
    pub protocol: Option<Value>,
    #[serde(alias = "interface")]
    pub interface_number: Option<Value>,
    pub bind_protocol: Option<String>,
}

#[derive(Deserialize, Debug, Clone, PartialEq, Default)]
pub struct AcpiBind {
    pub hid: Option<Value>,
    pub first_cid: Option<Value>,
    pub bus_type: Option<Value>,
}

#[derive(Deserialize, Debug, Clone, PartialEq, Default)]
pub struct BindPrimary {
    pub node: String,
    pub compat: Option<Value>,
    pub vid: Option<Value>,
    pub pid: Option<Value>,
    pub did: Option<Value>,
    pub protocol: Option<String>,
    pub service: Option<String>,
    pub banjo: Option<String>,
    pub transport: Option<String>,
    pub pci: Option<PciBind>,
    pub usb: Option<UsbBind>,
    pub acpi: Option<AcpiBind>,
    pub node_name: Option<Value>,
    pub match_name: Option<bool>,
    pub one_of: Option<Vec<DmlBind>>,
    pub rules: Option<HashMap<String, Value>>,
}

#[derive(Deserialize, Debug, Clone, PartialEq, Default)]
pub struct DmlBind {
    pub protocol: Option<String>,
    pub service: Option<String>,
    pub banjo: Option<String>,
    pub transport: Option<String>,
    pub vid: Option<Value>,
    pub pid: Option<Value>,
    pub did: Option<Value>,
    pub compat: Option<Value>,
    pub pci: Option<PciBind>,
    pub usb: Option<UsbBind>,
    pub acpi: Option<AcpiBind>,
    pub node_name: Option<Value>,
    pub match_name: Option<bool>,
    pub primary: Option<BindPrimary>,
    pub one_of: Option<Vec<DmlBind>>,
    pub rules: Option<HashMap<String, Value>>,
    #[serde(alias = "name")]
    pub composite_name: Option<String>,
}

#[derive(Deserialize, Debug, Default, Clone)]
pub struct DmlProgram {
    pub driver_name: Option<String>,
    #[serde(alias = "requirements")]
    pub bind: Option<DmlBind>,
}

#[derive(Deserialize, Debug, Default)]
pub struct DmlInput {
    pub name: Option<String>,
    #[serde(alias = "composite_name")]
    #[allow(dead_code)]
    pub composite_name: Option<String>,
    #[serde(default)]
    pub program: DmlProgram,
    #[serde(default)]
    pub include: Vec<String>,
    #[serde(default)]
    pub children: Vec<DmlChild>,
    #[serde(default, alias = "offers")]
    pub offer: Vec<DmlOffer>,
    #[serde(default)]
    pub metadata_mappings: Vec<MetadataMapping>,
    #[serde(default, rename = "use")]
    pub use_entries: Vec<Value>,
    #[serde(default)]
    pub capabilities: Vec<Value>,
    #[serde(default)]
    pub expose: Vec<Value>,
    #[serde(default)]
    pub driver_configs: Vec<DriverConfigDef>,
    #[serde(default)]
    pub service_constraints: Vec<ServiceConstraintDef>,
    #[serde(default)]
    pub iommus: Vec<DmlIommu>,
}

#[derive(Deserialize, Serialize, Debug, Clone, PartialEq, Default)]
pub struct DmlArmSmmu {
    pub base_address: u64,
}

#[derive(Deserialize, Serialize, Debug, Clone, PartialEq, Default)]
pub struct DmlStubIommu {}

/// Definition of an IOMMU within DML.
#[derive(Deserialize, Serialize, Debug, Clone, PartialEq, Default)]
pub struct DmlIommu {
    pub name: String,

    /// ID of the IOMMU will be autogenerated if this is [`None`].
    pub id: Option<u32>,

    /// Must be [`None`] if [`stub_iommu`](Self::stub_iommu) is [`Some`].
    pub arm_smmu: Option<DmlArmSmmu>,

    /// Must be [`None`] if [`arm_smmu`](Self::arm_smmu) is [`Some`].
    pub stub_iommu: Option<DmlStubIommu>,
}

impl DmlIommu {
    pub fn validate(&self) -> Result<(), anyhow::Error> {
        match (&self.arm_smmu, &self.stub_iommu) {
            (Some(_), None) | (None, Some(_)) => Ok(()),
            (Some(_), Some(_)) => {
                anyhow::bail!(
                    "IOMMU '{}' cannot specify both 'arm_smmu' and 'stub_iommu'",
                    self.name
                );
            }
            (None, None) => {
                anyhow::bail!(
                    "IOMMU '{}' must specify either 'arm_smmu' or 'stub_iommu'",
                    self.name
                );
            }
        }
    }
}

impl DmlInput {
    pub fn validate(&self) -> Result<(), anyhow::Error> {
        for config in &self.driver_configs {
            config.validate()?;
        }
        for constraint in &self.service_constraints {
            constraint.validate()?;
        }
        for iommu in &self.iommus {
            iommu.validate()?;
        }
        Ok(())
    }
}

#[derive(Deserialize, Debug, Clone)]
pub struct DmlStaticMetadata {
    pub id: String,
    pub data: Option<Vec<u8>>,
}

#[derive(Deserialize, Debug, Clone)]
pub struct DmlChild {
    pub name: String,
    pub id: Option<u32>,
    pub url: Option<String>,
    pub compatible: Option<String>,
    #[serde(default)]
    pub metadata: Vec<DmlStaticMetadata>,
    pub disabled: Option<bool>,
    pub driver_host: Option<String>,
}

#[derive(Deserialize, Serialize, Debug, Clone, PartialEq, Default)]
pub struct DmlOffer {
    #[serde(default)]
    pub from: Option<String>,
    pub to: String,
    #[serde(default)]
    pub service: Option<String>,
    #[serde(default)]
    pub driver_config: Option<String>,
    #[serde(default)]
    pub constraints: Option<Value>,
    #[serde(default)]
    pub properties: Option<Value>,
    #[serde(default)]
    pub metadata: Option<DriverMetadataSchemaDef>,
    #[serde(default)]
    pub name: Option<String>,
    #[serde(flatten, default)]
    pub extra: HashMap<String, Value>,
}

#[derive(Deserialize, Debug)]
pub struct DriverDml {
    pub name: String,
    #[serde(default, alias = "composite_name")]
    pub composite_name: Option<String>,
    #[serde(default)]
    pub include: Vec<String>,
    #[serde(default)]
    pub program: Value,
    #[serde(default)]
    pub capabilities: Vec<Value>,
    #[serde(default, rename = "use")]
    pub use_entries: Vec<Value>,
    #[serde(default)]
    pub expose: Vec<Value>,
    #[serde(default)]
    pub config: Option<Value>,
    #[serde(default)]
    pub driver_configs: Vec<DriverConfigDef>,
    #[serde(default)]
    pub service_constraints: Vec<ServiceConstraintDef>,
}

#[derive(Deserialize, Serialize, Debug, Clone, PartialEq, Default)]
pub struct DriverCapability {
    #[serde(rename = "service", default)]
    pub service: Option<String>,
    #[serde(default, alias = "metadata")]
    pub constraints: Option<DriverMetadataSchemaDef>,
}

#[derive(Deserialize, Serialize, Debug, Clone, PartialEq, Default)]
pub struct DriverMetadataSchemaDef {
    #[serde(default)]
    pub id: Option<String>,
    #[serde(default)]
    pub schema: Option<Value>,
    #[serde(flatten, default)]
    pub extra: HashMap<String, Value>,
}

impl DriverMetadataSchemaDef {
    pub fn id(&self) -> Option<&str> {
        self.id.as_deref()
    }
}

#[derive(Deserialize, Debug, Clone)]
pub struct MetadataAggregationDef {
    pub service: String,
    pub field: String,
    #[serde(default)]
    pub use_node_name: bool,
    pub auto_increment: Option<String>,
}

#[derive(Deserialize, Debug, Clone)]
pub struct MetadataMapping {
    pub metadata_id: String,
    pub aggregations: Vec<MetadataAggregationDef>,
}

// Simplified AST for JSON Schema
#[derive(Debug, Clone, PartialEq)]
pub enum Type {
    Bool,
    Uint8,
    Uint16,
    Uint32,
    Uint64,
    Int8,
    Int16,
    Int32,
    Int64,
    String,
    Vector(Box<Type>),
    Struct(String),
    Enum(String),
    ProviderId,
}

#[derive(Debug, Clone, PartialEq)]
pub struct Field {
    pub name: String,
    pub ty: Type,
    pub optional: bool,
}

#[derive(Debug, Clone, PartialEq)]
pub struct StructDef {
    pub name: String,
    pub fields: Vec<Field>,
}

#[derive(Debug, Clone, PartialEq)]
pub struct EnumDef {
    pub name: String,
    pub variants: Vec<String>,
}

pub const DEFAULT_ROOT_STRUCT_NAME: &str = "Root";

pub fn capitalize(s: &str) -> String {
    let mut c = s.chars();
    match c.next() {
        None => String::new(),
        Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
    }
}

#[derive(Debug, Clone, PartialEq)]
pub struct Schema {
    pub id: String,
    pub enums: HashMap<String, EnumDef>,
    pub structs: HashMap<String, StructDef>,
    pub root_layout: StructDef,
}

impl Schema {
    /// Determines the name for the generated root metadata struct.
    ///
    /// Naming precedence:
    /// 1. If the schema explicitly specifies a `title` property, use that title.
    /// 2. If there is only a single schema (`total_schemas == 1`), default to
    ///    `<DriverName>Metadata` (preserving backwards compatibility).
    /// 3. If there are multiple schemas and `title` is omitted, fall back to
    ///    the capitalized last dot-separated segment of the schema `id`.
    pub fn root_struct_name(&self, normalized_driver_name: &str, total_schemas: usize) -> String {
        if self.root_layout.name != DEFAULT_ROOT_STRUCT_NAME {
            self.root_layout.name.clone()
        } else if total_schemas == 1 {
            format!("{}Metadata", capitalize(normalized_driver_name))
        } else {
            let last_part = self.id.rsplit('.').next().unwrap_or(normalized_driver_name);
            capitalize(last_part)
        }
    }
}

pub fn load_dml_file(
    path: &Path,
    visiting: &mut HashSet<PathBuf>,
    processed: &mut HashSet<PathBuf>,
) -> Result<DmlInput, anyhow::Error> {
    let canonical = path.canonicalize()?;
    if visiting.contains(&canonical) {
        anyhow::bail!("Circular include detected: {}", canonical.display());
    }
    if processed.contains(&canonical) {
        return Ok(DmlInput::default());
    }

    visiting.insert(canonical.clone());

    let file = File::open(path).with_context(|| format!("Failed to open {}", path.display()))?;
    let mut input: DmlInput = serde_json5::from_reader(file)
        .with_context(|| format!("Failed to parse {}", path.display()))?;

    let parent_dir = canonical
        .parent()
        .ok_or_else(|| anyhow::anyhow!("Path has no parent: {}", canonical.display()))?;
    let mut all_children = Vec::new();
    let mut all_offers = Vec::new();
    let mut all_mappings = Vec::new();
    let mut all_use_entries = Vec::new();
    let mut all_capabilities = Vec::new();
    let mut all_expose = Vec::new();
    let mut all_driver_configs = Vec::new();
    let mut all_service_constraints = Vec::new();
    let mut all_iommus = Vec::new();

    for include in &input.include {
        let include_path = parent_dir.join(include);
        let include_input = load_dml_file(&include_path, visiting, processed)?;
        all_children.extend(include_input.children);
        all_offers.extend(include_input.offer);
        all_mappings.extend(include_input.metadata_mappings);
        all_use_entries.extend(include_input.use_entries);
        all_capabilities.extend(include_input.capabilities);
        all_expose.extend(include_input.expose);
        all_driver_configs.extend(include_input.driver_configs);
        all_service_constraints.extend(include_input.service_constraints);
        all_iommus.extend(include_input.iommus);
    }

    all_children.extend(input.children);
    all_offers.extend(input.offer);
    all_mappings.extend(input.metadata_mappings);
    all_use_entries.extend(input.use_entries);
    all_capabilities.extend(input.capabilities);
    all_expose.extend(input.expose);
    all_driver_configs.extend(input.driver_configs);
    all_service_constraints.extend(input.service_constraints);
    all_iommus.extend(input.iommus);

    input.children = all_children;
    input.offer = all_offers;
    input.metadata_mappings = all_mappings;
    input.use_entries = all_use_entries;
    input.capabilities = all_capabilities;
    input.expose = all_expose;
    input.driver_configs = all_driver_configs;
    input.service_constraints = all_service_constraints;
    input.iommus = all_iommus;

    input.validate()?;

    visiting.remove(&canonical);
    processed.insert(canonical);

    Ok(input)
}

pub fn load_dml_file_root(path: &Path) -> Result<DmlInput, anyhow::Error> {
    let mut visiting = HashSet::new();
    let mut processed = HashSet::new();
    load_dml_file(path, &mut visiting, &mut processed)
}

pub fn load_driver_dml(path: &Path) -> Result<DriverDml, anyhow::Error> {
    let file = File::open(path).with_context(|| format!("Failed to open {}", path.display()))?;
    let mut driver_dml: DriverDml = serde_json5::from_reader(file)
        .with_context(|| format!("Failed to parse {}", path.display()))?;
    for cap_val in &driver_dml.capabilities {
        if let Some(obj) = cap_val.as_object() {
            if obj.contains_key("driver_config") {
                let config_def: DriverConfigDef = serde_json::from_value(cap_val.clone())
                    .with_context(|| {
                        format!("Failed to parse driver_config capability in {}", path.display())
                    })?;
                driver_dml.driver_configs.push(config_def);
            } else if obj.contains_key("service")
                && (obj.contains_key("constraints")
                    || obj.contains_key("properties")
                    || obj.contains_key("defs"))
            {
                let constraint_def: ServiceConstraintDef = serde_json::from_value(cap_val.clone())
                    .with_context(|| {
                        format!(
                            "Failed to parse service constraint capability in {}",
                            path.display()
                        )
                    })?;
                driver_dml.service_constraints.push(constraint_def);
            }
        }
    }
    for config in &driver_dml.driver_configs {
        config.validate()?;
    }
    for constraint in &driver_dml.service_constraints {
        constraint.validate()?;
    }
    Ok(driver_dml)
}

pub fn parse_json_schema(schema_val: &Value, config_id: &str) -> Result<Schema, anyhow::Error> {
    let mut enums = HashMap::new();
    let mut structs = HashMap::new();

    if let Some(defs) = schema_val.get("definitions").and_then(|v| v.as_object()) {
        // Pass 1: Parse all enums
        for (name, def) in defs {
            if let Some(variants) = def.get("enum").and_then(|v| v.as_array()) {
                let variants: Vec<String> = variants
                    .iter()
                    .map(|v| {
                        v.as_str()
                            .ok_or_else(|| anyhow::anyhow!("Enum variant must be string"))
                            .map(|s| s.to_string())
                    })
                    .collect::<Result<_, _>>()?;
                enums.insert(name.clone(), EnumDef { name: name.clone(), variants });
            }
        }
        // Pass 2: Parse all structs
        for (name, def) in defs {
            if def.get("type").and_then(|v| v.as_str()) == Some("object") {
                let fields = parse_properties(def, &enums)?;
                structs.insert(name.clone(), StructDef { name: name.clone(), fields });
            }
        }
    }

    if schema_val.get("type").and_then(|v| v.as_str()) != Some("object") {
        anyhow::bail!("Root schema must be of type 'object'");
    }
    let root_name = schema_val
        .get("title")
        .and_then(|v| v.as_str())
        .map(|s| s.to_string())
        .unwrap_or_else(|| DEFAULT_ROOT_STRUCT_NAME.to_string());
    let root_fields = parse_properties(schema_val, &enums)?;
    let root_layout = StructDef { name: root_name, fields: root_fields };

    Ok(Schema { id: config_id.to_string(), enums, structs, root_layout })
}

fn parse_properties(
    obj_val: &Value,
    enums: &HashMap<String, EnumDef>,
) -> Result<Vec<Field>, anyhow::Error> {
    let mut fields = Vec::new();
    let properties = obj_val
        .get("properties")
        .and_then(|v| v.as_object())
        .ok_or_else(|| anyhow::anyhow!("Missing 'properties' in object definition"))?;
    let required: HashSet<String> = match obj_val.get("required") {
        Some(Value::Array(arr)) => {
            let mut required_fields = HashSet::new();
            for v in arr {
                let s = v.as_str().ok_or_else(|| {
                    anyhow::anyhow!(
                        "JSON Schema 'required' array elements must be strings: {:?}",
                        v
                    )
                })?;
                required_fields.insert(s.to_string());
            }
            required_fields
        }
        Some(_) => anyhow::bail!("JSON Schema 'required' must be an array"),
        None => HashSet::new(),
    };

    for (name, prop) in properties {
        let ty = parse_type(prop, enums)?;
        let optional = !required.contains(name);
        fields.push(Field { name: name.clone(), ty, optional });
    }
    Ok(fields)
}

fn parse_type(prop_val: &Value, enums: &HashMap<String, EnumDef>) -> Result<Type, anyhow::Error> {
    if let Some(ref_path) = prop_val.get("$ref").and_then(|v| v.as_str()) {
        let name = ref_path
            .split('/')
            .next_back()
            .ok_or_else(|| anyhow::anyhow!("Invalid $ref: {}", ref_path))?;
        if enums.contains_key(name) {
            return Ok(Type::Enum(name.to_string()));
        } else {
            return Ok(Type::Struct(name.to_string()));
        }
    }

    let type_str = prop_val
        .get("type")
        .and_then(|v| v.as_str())
        .ok_or_else(|| anyhow::anyhow!("Missing 'type' in property: {:?}", prop_val))?;

    match type_str {
        "boolean" => Ok(Type::Bool),
        "string" => Ok(Type::String),
        "integer" => {
            if let Some(fuchsia_type) = prop_val.get("fuchsia_type").and_then(|v| v.as_str()) {
                match fuchsia_type {
                    "uint8" => Ok(Type::Uint8),
                    "uint16" => Ok(Type::Uint16),
                    "uint32" => Ok(Type::Uint32),
                    "uint64" => Ok(Type::Uint64),
                    "int8" => Ok(Type::Int8),
                    "int16" => Ok(Type::Int16),
                    "int32" => Ok(Type::Int32),
                    "int64" => Ok(Type::Int64),
                    "provider_id" => Ok(Type::ProviderId),
                    _ => anyhow::bail!("Unsupported fuchsia_type: {}", fuchsia_type),
                }
            } else {
                Ok(Type::Uint32)
            }
        }
        "array" => {
            let items_val = prop_val
                .get("items")
                .ok_or_else(|| anyhow::anyhow!("Missing 'items' in array property"))?;
            let item_ty = parse_type(items_val, enums)?;
            Ok(Type::Vector(Box::new(item_ty)))
        }
        _ => anyhow::bail!("Unsupported JSON Schema type: {}", type_str),
    }
}

pub fn parse_driver_config_schema(config: &DriverConfigDef) -> Result<Schema, anyhow::Error> {
    let mut enums = HashMap::new();
    let mut structs = HashMap::new();

    if let Some(defs) = &config.defs {
        // Pass 1: Parse all enums from defs
        for (name, def) in defs {
            if let Some(variants_val) = &def.enum_values {
                if let Some(arr) = variants_val.as_array() {
                    let variants: Vec<String> = arr
                        .iter()
                        .map(|v| {
                            v.as_str()
                                .ok_or_else(|| anyhow::anyhow!("Enum variant must be string"))
                                .map(|s| s.to_string())
                        })
                        .collect::<Result<_, _>>()?;
                    enums.insert(name.clone(), EnumDef { name: name.clone(), variants });
                }
            }
        }
        // Pass 2: Parse all structs from defs (excluding enums and bits)
        for (name, def) in defs {
            if def.enum_values.is_none() && def.property_type.as_deref() != Some("bits") {
                let fields = parse_property_def_fields(def, &enums, config.defs.as_ref())?;
                structs.insert(name.clone(), StructDef { name: name.clone(), fields });
            }
        }
    }

    let root_name = DEFAULT_ROOT_STRUCT_NAME.to_string();
    let mut root_fields = Vec::new();
    let required_set: HashSet<&str> = config
        .required
        .as_ref()
        .map(|r| r.iter().map(|s| s.as_str()).collect())
        .unwrap_or_default();

    let mut sorted_props: Vec<_> = config.properties.iter().collect();
    sorted_props.sort_by_key(|&(k, _)| k);
    for (name, prop) in sorted_props {
        let ty = parse_property_def_type(prop, &enums, config.defs.as_ref())?;
        let optional = !required_set.contains(name.as_str());
        root_fields.push(Field { name: name.clone(), ty, optional });
    }

    let root_layout = StructDef { name: root_name, fields: root_fields };
    Ok(Schema { id: config.driver_config.clone(), enums, structs, root_layout })
}

pub fn parse_service_constraint_schema(
    constraint: &ServiceConstraintDef,
) -> Result<Schema, anyhow::Error> {
    let mut enums = HashMap::new();
    let mut structs = HashMap::new();

    if let Some(defs) = &constraint.defs {
        // Pass 1: Parse all enums from defs
        for (name, def) in defs {
            if let Some(variants_val) = &def.enum_values {
                if let Some(arr) = variants_val.as_array() {
                    let variants: Vec<String> = arr
                        .iter()
                        .map(|v| {
                            v.as_str()
                                .ok_or_else(|| anyhow::anyhow!("Enum variant must be string"))
                                .map(|s| s.to_string())
                        })
                        .collect::<Result<_, _>>()?;
                    enums.insert(name.clone(), EnumDef { name: name.clone(), variants });
                }
            }
        }
        // Pass 2: Parse all structs from defs (excluding enums and bits)
        for (name, def) in defs {
            if def.enum_values.is_none() && def.property_type.as_deref() != Some("bits") {
                let fields = parse_property_def_fields(def, &enums, constraint.defs.as_ref())?;
                structs.insert(name.clone(), StructDef { name: name.clone(), fields });
            }
        }
    }

    let root_name = DEFAULT_ROOT_STRUCT_NAME.to_string();
    let mut root_fields = Vec::new();
    let required_set: HashSet<&str> = constraint
        .required
        .as_ref()
        .map(|r| r.iter().map(|s| s.as_str()).collect())
        .unwrap_or_default();

    let mut sorted_props: Vec<_> = constraint.constraints.iter().collect();
    sorted_props.sort_by_key(|&(k, _)| k);
    for (name, prop) in sorted_props {
        let ty = parse_property_def_type(prop, &enums, constraint.defs.as_ref())?;
        let optional = !required_set.contains(name.as_str());
        root_fields.push(Field { name: name.clone(), ty, optional });
    }

    let root_layout = StructDef { name: root_name, fields: root_fields };
    Ok(Schema { id: constraint.service.clone(), enums, structs, root_layout })
}

fn parse_property_def_fields(
    def: &PropertyDef,
    enums: &HashMap<String, EnumDef>,
    defs: Option<&HashMap<String, PropertyDef>>,
) -> Result<Vec<Field>, anyhow::Error> {
    let mut fields = Vec::new();
    let required_set: HashSet<&str> =
        def.required.as_ref().map(|r| r.iter().map(|s| s.as_str()).collect()).unwrap_or_default();

    if let Some(props) = &def.properties {
        let mut sorted_props: Vec<_> = props.iter().collect();
        sorted_props.sort_by_key(|&(k, _)| k);
        for (name, prop) in sorted_props {
            let ty = parse_property_def_type(prop, enums, defs)?;
            let optional = !required_set.contains(name.as_str());
            fields.push(Field { name: name.clone(), ty, optional });
        }
    }
    Ok(fields)
}

fn parse_property_def_type(
    prop: &PropertyDef,
    enums: &HashMap<String, EnumDef>,
    defs: Option<&HashMap<String, PropertyDef>>,
) -> Result<Type, anyhow::Error> {
    if let Some(ref_path) = &prop.reference {
        let name = ref_path
            .split('/')
            .next_back()
            .ok_or_else(|| anyhow::anyhow!("Invalid ref: {}", ref_path))?;
        if enums.contains_key(name) {
            return Ok(Type::Enum(name.to_string()));
        } else if let Some(target_def) = defs.and_then(|d| d.get(name)) {
            if target_def.property_type.as_deref() == Some("bits") {
                return match target_def.underlying_type.as_deref() {
                    Some("uint8") => Ok(Type::Uint8),
                    Some("uint16") => Ok(Type::Uint16),
                    Some("uint64") => Ok(Type::Uint64),
                    _ => Ok(Type::Uint32),
                };
            } else {
                return Ok(Type::Struct(name.to_string()));
            }
        } else {
            return Ok(Type::Struct(name.to_string()));
        }
    }

    let type_str = prop
        .property_type
        .as_deref()
        .ok_or_else(|| anyhow::anyhow!("Missing 'type' in property definition: {:?}", prop))?;

    match type_str {
        "bool" | "boolean" => Ok(Type::Bool),
        "string" => Ok(Type::String),
        "uint8" => Ok(Type::Uint8),
        "uint16" => Ok(Type::Uint16),
        "uint32" => Ok(Type::Uint32),
        "uint64" => Ok(Type::Uint64),
        "int8" => Ok(Type::Int8),
        "int16" => Ok(Type::Int16),
        "int32" => Ok(Type::Int32),
        "int64" => Ok(Type::Int64),
        "provider_id" => Ok(Type::ProviderId),
        "bits" => match prop.underlying_type.as_deref() {
            Some("uint8") => Ok(Type::Uint8),
            Some("uint16") => Ok(Type::Uint16),
            Some("uint64") => Ok(Type::Uint64),
            _ => Ok(Type::Uint32),
        },
        "vector" | "array" => {
            let elem = prop
                .element
                .as_ref()
                .ok_or_else(|| anyhow::anyhow!("Missing 'element' in vector property"))?;
            let item_ty = parse_property_def_type(elem, enums, defs)?;
            Ok(Type::Vector(Box::new(item_ty)))
        }
        "object" => Ok(Type::Struct("object".to_string())),
        _ => anyhow::bail!("Unsupported property type: {}", type_str),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;

    #[test]
    fn test_circular_include_error() {
        let temp_dir = std::env::temp_dir().join("test_temp_circular");
        fs::create_dir_all(&temp_dir).unwrap();

        let file1 = temp_dir.join("a.dml");
        let file2 = temp_dir.join("b.dml");

        // a.dml includes b.dml
        fs::write(&file1, r#"{"include": ["b.dml"]}"#).unwrap();
        // b.dml includes a.dml
        fs::write(&file2, r#"{"include": ["a.dml"]}"#).unwrap();

        let res = load_dml_file_root(&file1);

        // Clean up
        let _ = fs::remove_file(&file1);
        let _ = fs::remove_file(&file2);
        let _ = fs::remove_dir(&temp_dir);

        assert!(res.is_err());
        let err_msg = format!("{}", res.err().unwrap());
        assert!(
            err_msg.contains("Circular include detected"),
            "Expected circular include error, got: {}",
            err_msg
        );
    }

    #[test]
    fn test_diamond_include_success() {
        let temp_dir = std::env::temp_dir().join("test_temp_diamond");
        fs::create_dir_all(&temp_dir).unwrap();

        let file_a = temp_dir.join("a.dml");
        let file_b = temp_dir.join("b.dml");
        let file_c = temp_dir.join("c.dml");
        let file_d = temp_dir.join("d.dml");

        // d.dml has some children
        fs::write(&file_d, r#"{"children": [{"name": "child_d"}]}"#).unwrap();
        // b.dml includes d.dml
        fs::write(&file_b, r#"{"include": ["d.dml"]}"#).unwrap();
        // c.dml includes d.dml
        fs::write(&file_c, r#"{"include": ["d.dml"]}"#).unwrap();
        // a.dml includes b.dml and c.dml
        fs::write(&file_a, r#"{"include": ["b.dml", "c.dml"]}"#).unwrap();

        let res = load_dml_file_root(&file_a);

        // Clean up
        let _ = fs::remove_file(&file_a);
        let _ = fs::remove_file(&file_b);
        let _ = fs::remove_file(&file_c);
        let _ = fs::remove_file(&file_d);
        let _ = fs::remove_dir(&temp_dir);

        assert!(res.is_ok());
        let input = res.unwrap();
        // child_d should be included exactly once because of the processed cache
        let child_names: Vec<String> = input.children.iter().map(|c| c.name.clone()).collect();
        assert_eq!(child_names, vec!["child_d"]);
    }

    #[test]
    fn test_dml_schema_is_valid_json() {
        let schema_str = include_str!("../dml.schema.json");
        let parsed: Result<serde_json::Value, _> = serde_json::from_str(schema_str);
        assert!(parsed.is_ok(), "dml.schema.json is not valid JSON: {:?}", parsed.err());
        let val = parsed.unwrap();
        assert_eq!(
            val.get("$schema").and_then(|v| v.as_str()),
            Some("http://json-schema.org/draft-07/schema#")
        );
        let defs = val
            .get("definitions")
            .and_then(|v| v.as_object())
            .expect("missing definitions in schema");
        for key in [
            "PciBind",
            "UsbBind",
            "AcpiBind",
            "DmlBind",
            "Program",
            "UseEntry",
            "BoardChild",
            "BoardOffer",
            "MetadataMapping",
        ] {
            assert!(defs.contains_key(key), "Missing key definition '{}' in dml.schema.json", key);
        }
    }
    #[test]
    fn test_board_dml_offer_and_offers_alias() {
        let json_offer = r##"{
            "offer": [
                {
                    "from": "parent",
                    "to": "#child",
                    "service": "fuchsia.hardware.gpio.Service"
                }
            ]
        }"##;
        let parsed_offer: DmlInput = serde_json5::from_str(json_offer).unwrap();
        assert_eq!(parsed_offer.offer.len(), 1);
        assert_eq!(parsed_offer.offer[0].to, "#child");

        let json_offers = r##"{
            "offers": [
                {
                    "from": "parent",
                    "to": "#child2",
                    "service": "fuchsia.hardware.gpio.Service"
                }
            ]
        }"##;
        let parsed_offers: DmlInput = serde_json5::from_str(json_offers).unwrap();
        assert_eq!(parsed_offers.offer.len(), 1);
        assert_eq!(parsed_offers.offer[0].to, "#child2");
    }

    #[test]
    fn test_board_dml_include_offer_merging() {
        let temp_dir = std::env::temp_dir().join("test_temp_offer_merging");
        let _ = fs::remove_dir_all(&temp_dir);
        fs::create_dir_all(&temp_dir).unwrap();

        let shard_offer = temp_dir.join("shard_offer.dml");
        let shard_offers = temp_dir.join("shard_offers.dml");
        let root_file = temp_dir.join("root.dml");

        // shard_offer.dml uses modern "offer"
        fs::write(
            &shard_offer,
            r##"{
                "offer": [
                    {
                        "from": "parent",
                        "to": "#child1",
                        "service": "fuchsia.hardware.gpio.Service"
                    }
                ]
            }"##,
        )
        .unwrap();

        // shard_offers.dml uses legacy "offers"
        fs::write(
            &shard_offers,
            r##"{
                "offers": [
                    {
                        "from": "parent",
                        "to": "#child2",
                        "service": "fuchsia.hardware.i2c.Service"
                    }
                ]
            }"##,
        )
        .unwrap();

        // root.dml includes both shards and defines its own "offer"
        fs::write(
            &root_file,
            r##"{
                "include": ["shard_offer.dml", "shard_offers.dml"],
                "offer": [
                    {
                        "from": "parent",
                        "to": "#child3",
                        "service": "fuchsia.hardware.clock.Service"
                    }
                ]
            }"##,
        )
        .unwrap();

        let res = load_dml_file_root(&root_file);

        // Clean up
        let _ = fs::remove_file(&shard_offer);
        let _ = fs::remove_file(&shard_offers);
        let _ = fs::remove_file(&root_file);
        let _ = fs::remove_dir(&temp_dir);

        assert!(res.is_ok(), "Failed to load root file with included offers: {:?}", res.err());
        let input = res.unwrap();
        assert_eq!(input.offer.len(), 3);
        assert_eq!(input.offer[0].to, "#child1");
        assert_eq!(input.offer[1].to, "#child2");
        assert_eq!(input.offer[2].to, "#child3");
    }

    #[test]
    fn test_parse_service_constraints_sample() {
        let sample = r#"{
  name: "vim3",
  program: {
    driver_name: "vim3-dml",
    bind: {
      service: "fuchsia.hardware.platform.bus.Service",
      transport: "Driver",
      vid: "fuchsia.khadas.platform.BIND_PLATFORM_DEV_VID.KHADAS",
      pid: "fuchsia.khadas.platform.BIND_PLATFORM_DEV_PID.VIM3"
    }
  },
  include: [
    "adc.shard.dml",
    "audio.shard.dml",
    "bluetooth.shard.dml",
    "buttons.shard.dml",
    "canvas.shard.dml",
    "clock.shard.dml",
    "cpu.shard.dml",
    "display.shard.dml",
    "dt-root.shard.dml",
    "ethernet.shard.dml",
    "gic.shard.dml",
    "gpio.shard.dml",
    "gpu.shard.dml",
    "hrtimer.shard.dml",
    "i2c.shard.dml",
    "mcu.shard.dml",
    "nna.shard.dml",
    "power.shard.dml",
    "pwm.shard.dml",
    "registers.shard.dml",
    "rtc.shard.dml",
    "sdmmc.shard.dml",
    "suspend.shard.dml",
    "thermal.shard.dml",
    "usb.shard.dml",
    "video.shard.dml",
    "wifi.shard.dml"
  ],
  service_constraints: [
    {
      service: "fuchsia.hardware.pin.PinStatesService",
      constraints: {
        name: {
          type: "string",
          max_size: 64
        },
        states: {
          type: "vector",
          element: {
            ref: "fuchsia.hardware.pinimpl.Metadata/DevicePinStates"
          },
          max_count: 1000
        }
      }
    }
  ]
}"#;

        let input: DmlInput = serde_json5::from_str(sample).expect("Failed to parse DML sample");
        assert_eq!(input.name, Some("vim3".to_string()));
        assert_eq!(input.include.len(), 27);
        assert_eq!(input.service_constraints.len(), 1);

        let constraint_def = &input.service_constraints[0];
        assert_eq!(constraint_def.service.as_str(), "fuchsia.hardware.pin.PinStatesService");
        assert_eq!(constraint_def.constraints.len(), 2);

        let name_prop = constraint_def.constraints.get("name").expect("Missing 'name' property");
        assert_eq!(name_prop.property_type, Some("string".to_string()));
        assert_eq!(name_prop.max_size, Some(Bound::Limit(64)));
        assert_eq!(name_prop.to_type().unwrap(), Type::String);

        let states_prop =
            constraint_def.constraints.get("states").expect("Missing 'states' property");
        assert_eq!(states_prop.property_type, Some("vector".to_string()));
        assert_eq!(states_prop.max_count, Some(Bound::Limit(1000)));
        let elem = states_prop.element.as_ref().expect("Missing 'element' in states");
        assert_eq!(
            elem.reference,
            Some("fuchsia.hardware.pinimpl.Metadata/DevicePinStates".to_string())
        );
        assert_eq!(
            states_prop.to_type().unwrap(),
            Type::Vector(Box::new(Type::Struct("DevicePinStates".to_string())))
        );
    }

    #[test]
    fn test_service_constraints_included() {
        let temp_dir = std::env::temp_dir().join("test_temp_service_constraints_included");
        fs::create_dir_all(&temp_dir).unwrap();

        let shard_file = temp_dir.join("gpio.shard.dml");
        let main_file = temp_dir.join("main.dml");

        fs::write(
            &shard_file,
            r#"{
            service_constraints: [
                {
                    service: "fuchsia.hardware.gpio.Service",
                    constraints: {
                        pin: {
                            type: "uint32"
                        }
                    }
                }
            ]
        }"#,
        )
        .unwrap();

        fs::write(
            &main_file,
            r#"{
            include: ["gpio.shard.dml"],
            service_constraints: [
                {
                    service: "fuchsia.hardware.pin.PinStatesService",
                    constraints: {
                        name: {
                            type: "string",
                            max_size: 64
                        }
                    }
                }
            ]
        }"#,
        )
        .unwrap();

        let res = load_dml_file_root(&main_file);

        // Clean up
        let _ = fs::remove_file(&shard_file);
        let _ = fs::remove_file(&main_file);
        let _ = fs::remove_dir(&temp_dir);

        assert!(res.is_ok());
        let input = res.unwrap();
        assert_eq!(input.service_constraints.len(), 2);
        assert_eq!(input.service_constraints[0].service.as_str(), "fuchsia.hardware.gpio.Service");
        assert_eq!(
            input.service_constraints[1].service.as_str(),
            "fuchsia.hardware.pin.PinStatesService"
        );
    }

    #[test]
    fn test_parse_offers_with_properties() {
        let sample = r##"{
  offers: [
    {
      to: "#gpio-buttons",
      service: "fuchsia.hardware.pinimpl.Metadata",
      properties: {
        controller_id: 0,
        pins: [
          {
            pin: 1,
            pull: "Up",
            buffer_mode: "Input"
          }
        ]
      }
    }
  ]
}"##;

        let input: DmlInput =
            serde_json5::from_str(sample).expect("Failed to parse offers with properties");
        assert_eq!(input.offer.len(), 1);
        let offer = &input.offer[0];
        assert_eq!(offer.to, "#gpio-buttons");
        assert_eq!(offer.service, Some("fuchsia.hardware.pinimpl.Metadata".to_string()));
        let props = offer.properties.as_ref().expect("Missing properties in offer");
        assert_eq!(props["controller_id"], 0);
        assert_eq!(props["pins"][0]["pin"], 1);
        assert_eq!(props["pins"][0]["pull"], "Up");
        assert_eq!(props["pins"][0]["buffer_mode"], "Input");
    }

    #[test]
    fn test_parse_config_offer() {
        let sample = r##"{
  offers: [
    {
      driver_config: "fuchsia.buttons.GpioButtonsMetadata",
      from: "#gpio-controller-ff634400",
      to: "#gpio-buttons",
      buttons: [
        {
          gpio_a_index: 0,
          id: "POWER"
        }
      ]
    }
  ]
}"##;
        let input: DmlInput = serde_json5::from_str(sample).expect("Failed to parse config offer");
        assert_eq!(input.offer.len(), 1);
        let offer = &input.offer[0];
        assert_eq!(offer.driver_config.as_deref(), Some("fuchsia.buttons.GpioButtonsMetadata"));
        assert_eq!(offer.from.as_deref(), Some("#gpio-controller-ff634400"));
        assert_eq!(offer.to, "#gpio-buttons");
        assert!(offer.extra.contains_key("buttons"));
    }

    #[test]
    fn test_parse_offers_with_metadata_snippet() {
        let sample = r##"{
  offers: [
    {
      to: "#gpio-buttons",
      service: "fuchsia.hardware.pinimpl.PinImpl",
      metadata: {
        id: "#/fuchsia.hardware.pinimpl.Metadata",
        controller_id: 0,
        pins: [
          {
            pin: 1,
            pull: "Up",
            buffer_mode: "Input"
          }
        ]
      }
    }
  ]
}"##;

        let input: DmlInput =
            serde_json5::from_str(sample).expect("Failed to parse offers with metadata");
        assert_eq!(input.offer.len(), 1);
        let offer = &input.offer[0];
        assert_eq!(offer.to, "#gpio-buttons");
        assert_eq!(offer.service.as_deref(), Some("fuchsia.hardware.pinimpl.PinImpl"));
        let meta = offer.metadata.as_ref().expect("Missing metadata in offer");
        assert_eq!(meta.id(), Some("#/fuchsia.hardware.pinimpl.Metadata"));
        assert_eq!(meta.extra.get("controller_id"), Some(&serde_json::json!(0)));
        let pins = meta.extra.get("pins").expect("Missing pins in metadata");
        assert_eq!(pins[0]["pin"], 1);
        assert_eq!(pins[0]["pull"], "Up");
        assert_eq!(pins[0]["buffer_mode"], "Input");
    }

    #[test]
    fn test_parse_offer_missing_to_fails() {
        let sample = r##"{
  offers: [
    {
      service: "fuchsia.hardware.gpio.Service",
      from: "#gpio-controller"
    }
  ]
}"##;
        let res: Result<DmlInput, _> = serde_json5::from_str(sample);
        assert!(res.is_err(), "Expected parsing to fail when 'to' field is missing from offer");
    }

    #[test]
    fn test_parse_buttons_driver_dml() {
        let sample = r##"{
  name: "buttons",
  capabilities: [
    {
      service: "fuchsia.hardware.buttons.Service",
    },
    {
      driver_config: "fuchsia.buttons.GpioButtonsMetadata",
      defs: {
        DirectGpioButton: {
          type: "object",
          properties: {},
        },
        MatrixGpioButton: {
          type: "object",
          properties: {
            gpio_b_index: {
              type: "uint8",
            },
          },
        },
        GpioButtonType: {
          type: "object",
          properties: {
            direct: {
              ref: "#/DirectGpioButton",
            },
            matrix: {
              ref: "#/MatrixGpioButton",
            },
          },
          oneOf: [
            [
              "direct",
              "matrix",
            ],
          ],
        },
        GpioButtonId: {
          type: "string",
          enum: [
            "VOLUME_UP",
            "VOLUME_DOWN",
            "FDR",
            "MIC_MUTE",
            "PLAY_PAUSE",
            "KEY_A",
            "KEY_M",
            "CAM_MUTE",
            "MIC_AND_CAM_MUTE",
            "FUNCTION",
            "POWER",
          ],
        },
        InterruptGpio: {
          type: "object",
          properties: {},
        },
        MatrixOutputGpio: {
          type: "object",
          properties: {
            output_value: {
              type: "uint8",
            },
          },
        },
        PollGpio: {
          type: "object",
          properties: {
            period: {
              type: "int64",
            },
          },
        },
        GpioType: {
          type: "object",
          properties: {
            interrupt: {
              ref: "#/InterruptGpio",
            },
            matrix_output: {
              ref: "#/MatrixOutputGpio",
            },
            poll: {
              ref: "#/PollGpio",
            },
          },
        },
        GpioFlag: {
          type: "bits",
          underlying_type: "uint32",
          bits: {
            INVERTED: 0x80,
          },
        },
        GpioButtonConfig: {
          type: "object",
          properties: {
            type: {
              ref: "#/GpioButtonType",
            },
            gpio_a_index: {
              type: "uint8",
            },
            gpio_delay: {
              type: "int64",
            },
            id: {
              ref: "#/GpioButtonId",
            },
          },
        },
        GpioConfig: {
          type: "object",
          properties: {
            type: {
              ref: "#/GpioType",
            },
            flags: {
              ref: "#/GpioFlag",
            },
          },
        },
      },
      properties: {
        buttons: {
          type: "vector",
          element: {
            ref: "#/GpioButtonConfig",
          },
          max_count: 1000,
        },
        gpios: {
          type: "vector",
          element: {
            ref: "#/GpioConfig",
          },
          max_count: 1000,
        },
      },
    },
  ],
}"##;

        let temp_dir = std::env::temp_dir().join("test_temp_buttons_dml");
        fs::create_dir_all(&temp_dir).unwrap();
        let file_path = temp_dir.join("buttons.dml");
        fs::write(&file_path, sample).unwrap();

        let driver_dml = load_driver_dml(&file_path).expect("Failed to parse buttons driver DML");
        assert_eq!(driver_dml.driver_configs.len(), 1);
        assert_eq!(
            driver_dml.driver_configs[0].driver_config,
            "fuchsia.buttons.GpioButtonsMetadata"
        );
        for config in &driver_dml.driver_configs {
            assert!(config.validate().is_ok());
        }

        let _ = fs::remove_file(&file_path);
        let _ = fs::remove_dir(&temp_dir);
    }

    #[test]
    fn test_load_driver_dml_invalid_schema() {
        let invalid_config_sample = r#"{
  name: "invalid_config_driver",
  capabilities: [
    {
      driver_config: 12345, // invalid type for driver_config (should be string)
      properties: {},
    },
  ],
}"#;

        let temp_dir = std::env::temp_dir().join("test_temp_invalid_dml");
        fs::create_dir_all(&temp_dir).unwrap();
        let file_path = temp_dir.join("invalid.dml");
        fs::write(&file_path, invalid_config_sample).unwrap();

        let res = load_driver_dml(&file_path);
        assert!(res.is_err());
        let err_msg = format!("{:#}", res.unwrap_err());
        assert!(err_msg.contains("Failed to parse driver_config capability"));

        let invalid_service_sample = r#"{
  name: "invalid_service_driver",
  capabilities: [
    {
      service: 12345, // invalid type for service (should be string)
      constraints: {},
    },
  ],
}"#;
        fs::write(&file_path, invalid_service_sample).unwrap();

        let res = load_driver_dml(&file_path);
        assert!(res.is_err());
        let err_msg = format!("{:#}", res.unwrap_err());
        assert!(err_msg.contains("Failed to parse service constraint capability"));

        let _ = fs::remove_file(&file_path);
        let _ = fs::remove_dir(&temp_dir);
    }

    #[test]
    fn test_dml_child_disabled() {
        let child_none = DmlChild {
            name: "test".to_string(),
            id: None,
            url: None,
            compatible: None,
            metadata: vec![],
            disabled: None,
            driver_host: None,
        };
        assert_eq!(child_none.disabled, None);
        assert_eq!(child_none.driver_host, None);

        let child_disabled = DmlChild { disabled: Some(true), ..child_none.clone() };
        assert_eq!(child_disabled.disabled, Some(true));

        let child_enabled = DmlChild { disabled: Some(false), ..child_none.clone() };
        assert_eq!(child_enabled.disabled, Some(false));

        // Test serde deserialization with JSON5 / JSON
        let parsed_disabled: DmlChild = serde_json5::from_str(
            r##"{
                name: "parsed_child",
                disabled: true,
                driver_host: "#gpio"
            }"##,
        )
        .unwrap();
        assert_eq!(parsed_disabled.disabled, Some(true));
        assert_eq!(parsed_disabled.driver_host.as_deref(), Some("#gpio"));

        let parsed_enabled: DmlChild = serde_json5::from_str(
            r#"{
                name: "parsed_enabled",
                disabled: false
            }"#,
        )
        .unwrap();
        assert_eq!(parsed_enabled.disabled, Some(false));
    }
}
