# Copyright 2023 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/bind/bind.gni")
import("//build/components.gni")
import("//build/drivers.gni")
import("//build/test.gni")

driver_bind_rules("vsock_usb_bind") {
  rules = "meta/vsock-usb.bind"
  bind_output = "vsock-usb.bindbc"
  tests = "meta/bind-tests.json"
  deps = [
    "//src/devices/bind/fuchsia.google.platform.usb",
    "//src/devices/bind/fuchsia.usb",
    "//src/devices/bind/fuchsia.usb.comm",
  ]
}

source_set("vsock-usb-lib") {
  configs += [ "//build/config:all_source" ]
  sources = [
    "vsock_usb.cc",
    "vsock_usb.h",
  ]
  public_deps = [
    ":vsock_usb_bind",
    "//sdk/fidl/fuchsia.driver.framework:fuchsia.driver.framework_cpp",
    "//sdk/fidl/fuchsia.hardware.usb.descriptor:fuchsia.hardware.usb.descriptor_cpp",
    "//sdk/fidl/fuchsia.hardware.usb.endpoint:fuchsia.hardware.usb.endpoint_cpp",
    "//sdk/fidl/fuchsia.hardware.usb.function:fuchsia.hardware.usb.function_cpp",
    "//sdk/fidl/fuchsia.hardware.vsockbridge:fuchsia.hardware.vsockbridge_cpp",
    "//sdk/lib/async",
    "//sdk/lib/async:async-cpp",
    "//sdk/lib/async-loop:async-loop-cpp",
    "//sdk/lib/async-loop:async-loop-default",
    "//sdk/lib/driver/compat/cpp",
    "//sdk/lib/driver/component/cpp",
    "//sdk/lib/driver/devfs/cpp",
    "//sdk/lib/driver/logging/cpp",
    "//sdk/lib/inspect/component/cpp",
    "//src/devices/bind/fuchsia.google.platform.usb:fuchsia.google.platform.usb_cpp",
    "//src/devices/usb/lib/usb:usb-dfv2-compat-logging",
    "//src/devices/usb/lib/usb-endpoint:usb-endpoint-client-dfv2-compat-logging",
    "//src/devices/usb/lib/usb-inspect",
    "//zircon/system/ulib/fbl",
    "//zircon/system/ulib/zx",
  ]
}

fuchsia_cc_driver("vsock-usb-driver") {
  output_name = "vsock-usb"

  configs += [
    "//build/config:all_source",
    "//build/config/fuchsia:enable_zircon_asserts",
  ]
  deps = [ ":vsock-usb-lib" ]
}

fuchsia_driver_component("vsock-usb") {
  component_name = "vsock-usb"
  deps = [ ":vsock-usb-driver" ]
  info = "meta/vsock-usb-info.json"
  manifest = "meta/vsock-usb.cml"
}

test("vsock-usb-test-bin") {
  testonly = true
  sources = [ "vsock_usb_test.cc" ]
  deps = [
    ":vsock-usb-lib",
    "//sdk/lib/async-default",
    "//sdk/lib/async-loop:async-loop-cpp",
    "//sdk/lib/async-loop:async-loop-default",
    "//sdk/lib/driver/testing/cpp",
    "//sdk/lib/inspect/testing/cpp",
    "//src/devices/usb/lib/usb-endpoint:fake-usb-endpoint-server",
    "//src/lib/fxl/test:gtest_main",
  ]
}

fuchsia_unittest_package("vsock-usb-test") {
  deps = [ ":vsock-usb-test-bin" ]
  test_specs = {
    environments = basic_envs
    log_settings = {
      max_severity = "ERROR"
    }
  }
}

group("tests") {
  testonly = true
  deps = [
    ":vsock-usb-test",
    ":vsock_usb_bind_test",
  ]
}
