# Copyright 2022 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

[package]
name = "with-tests"
version = "0.1.0"
edition = "2024"

[workspace]
members = [
    "sub-crate-binary",
    "sub-crate-library",
    "sub-crate-with-library-and-binary",
    "test-helpers",
]

[dependencies]
sub-crate-binary = { path = "./sub-crate-binary" }
sub-crate-library = { path = "./sub-crate-library" }
sub-crate-with-library-and-binary = { path = "./sub-crate-with-library-and-binary" }

[gn.package.sub-crate-binary."0.1.0"]
tests = true

[gn.package.sub-crate-binary."0.1.0".binary.foo-binary]
output_name = "foo-output"

[gn.package.sub-crate-binary."0.1.0".binary.foo-binary.platform."cfg(unix)"]
configs = [ "//applied/to/all" ]

[gn.package.sub-crate-binary."0.1.0".binary.foo-binary.platform."cfg(target_os = \"fuchsia\")"]
configs = [ "//extra/fuchsia/config" ]

[gn.package.sub-crate-library."0.1.0"]
tests = true

[gn.package.sub-crate-with-library-and-binary."0.1.0"]
tests = true

[gn.package.sub-crate-with-library-and-binary."0.1.0".binary.lib-and-bin-binary]
output_name = "lib-and-bin-output"
