# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("//build/bazel/rules/cc:fx_cc_library.bzl", "fx_cc_library")

package(default_applicable_licenses = ["//:license"])

fx_cc_library(
    name = "composite_fd",
    srcs = ["fd.cc"],
    hdrs = ["fd.h"],
    implementation_deps = [
        "//sdk/lib/fdio",
        "//sdk/lib/fit",
        "//sdk/lib/zxio",
        "//zircon/system/ulib/zx",
    ],
    visibility = ["//visibility:public"],
    alwayslink = True,
)
