# Copyright 2026 The Fuchsia Authors
#
# Use of this source code is governed by a MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT

import("//zircon/kernel/kernel_rust_crate.gni")

kernel_rust_crate("relaxed_atomic-rs") {
  edition = "2024"
  crate_name = "relaxed_atomic"
  source_root = "lib.rs"
  sources = [ "lib.rs" ]
  deps = [ "//third_party/rust_crates:paste" ]
  test_deps = [ "//zircon/kernel/lib/unittest:unittest-rs" ]
}
