# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# LINT.IfChange

load("//build/bazel/rules/cc:fx_cc_library.bzl", "fx_cc_library")

package(
    default_applicable_licenses = ["//:license"],
    default_visibility = ["//visibility:public"],
)

fx_cc_library(
    name = "common",
    srcs = [
        "channel.cc",
        "ieee80211_codes.cc",
        "logging.cc",
        "mac_frame.cc",
        "mcs_rate_lookup.cc",
    ],
    hdrs = [
        "include/wlan/common/action_frame.h",
        "include/wlan/common/bitfield.h",
        "include/wlan/common/channel.h",
        "include/wlan/common/element.h",
        "include/wlan/common/element_id.h",
        "include/wlan/common/ieee80211.h",
        "include/wlan/common/ieee80211_codes.h",
        "include/wlan/common/logging.h",
        "include/wlan/common/mac_frame.h",
        "include/wlan/common/mcs_rate_lookup.h",
    ],
    build_flags = ["//build/config/fuchsia:enable_zircon_asserts"],
    includes = ["include"],
    deps = [
        "//src/connectivity/wlan/drivers/lib/macaddr",
        "//zircon/system/ulib/fbl",
        "//zircon/system/ulib/zx",
        "@fuchsia_sdk//fidl/fuchsia.wlan.ieee80211:fuchsia.wlan.ieee80211_cpp",
        "@fuchsia_sdk//pkg/async-cpp",
        "@fuchsia_sdk//pkg/async-loop-cpp",
        "@fuchsia_sdk//pkg/async-loop-default",
    ],
)

# LINT.ThenChange(BUILD.gn)
