# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("//build/bazel/rules/rust:defs.bzl", "rustc_library")

package(default_applicable_licenses = ["//:license"])

rustc_library(
    name = "epoch",
    srcs = [
        "src/epoch.rs",
        "src/lib.rs",
    ],
    edition = "2024",
    lint_config = "//build/config/rust/lints:clippy_warn_all",
    test_deps = [
        "//third_party/rust_crates/vendor:proptest",
        "//third_party/rust_crates/vendor:serde_json",
    ],
    version = "0.1.0",
    visibility = [
        "//src/developer/ffx/plugins/assembly:__subpackages__",
        "//src/lib/assembly/product_bundle:__subpackages__",
        "//src/lib/assembly/update_package:__subpackages__",
        "//src/sys/pkg:__subpackages__",
    ],
    with_unit_tests = True,
    deps = [
        "//third_party/rust_crates/vendor:serde",
    ],
)
