// Copyright 2026 The Fuchsia Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package report

import (
	"context"
	"fmt"

	"go.fuchsia.dev/fuchsia/tools/check-licenses/config"
	"go.fuchsia.dev/fuchsia/tools/check-licenses/pipeline"
	"go.fuchsia.dev/fuchsia/tools/check-licenses/stages/validate"
)

// PolicyRenderer is a Stage 6 renderer that generates JSON configuration files
// for policy compliance exceptions.
type PolicyRenderer struct {
	Config *config.MasterConfig
}

// NewPolicyRenderer creates a new PolicyRenderer.
func NewPolicyRenderer(cfg *config.MasterConfig) *PolicyRenderer {
	return &PolicyRenderer{
		Config: cfg,
	}
}

func (r *PolicyRenderer) Run(ctx context.Context, projects []*pipeline.Project, errors []pipeline.ComplianceError) error {
	for _, e := range errors {
		target := e.FilePath
		if validate.IsProjectScopePolicy(e.CheckName) {
			target = e.Project
		}
		switch e.CheckName {
		case validate.PolicyNoLicense:
			fmt.Printf(" [Policy] Processing missing license: %s\n", target)
			_, _ = r.Config.AddPolicyException(e.CheckName, target, "TODO: Auto-generated by fx check-licenses fix", "Auto-generated exception via fix")

		case validate.PolicyNoReadme:
			fmt.Printf(" [Policy] Processing missing readme: %s\n", target)
			_, _ = r.Config.AddPolicyException(e.CheckName, target, "TODO: Auto-generated by fx check-licenses fix", "Auto-generated exception via fix")

		case validate.PolicyUnrecognizedLicense:
			fmt.Printf(" [Policy] Processing unrecognized license: %s\n", target)
			_, _ = r.Config.AddPolicyException(e.CheckName, target, "TODO: Auto-generated by fx check-licenses fix", "Auto-generated exception via fix")
		}
	}
	return nil
}
