# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/components.gni")
import("//src/starnix/build/starnix_linux_rustc_binary.gni")

starnix_linux_rustc_binary("suspend_for_socket_wakeup_binary") {
  edition = "2024"
  sources = [ "src/main.rs" ]
  deps = [ "//third_party/rust_crates:argh" ]
}

fuchsia_test_component("suspend_for_tcp_wakeup") {
  manifest = "meta/suspend_for_tcp_wakeup.cml"
  deps = [ ":suspend_for_socket_wakeup_binary" ]
}

fuchsia_test_component("suspend_for_udp_wakeup") {
  manifest = "meta/suspend_for_udp_wakeup.cml"
  deps = [ ":suspend_for_socket_wakeup_binary" ]
}
