# Copyright 2026 The Fuchsia Authors
#
# Use of this source code is governed by a MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT

# kernel_tests_enabled is true if the current toolchain has kernel tests
# enabled.
kernel_tests_enabled = toolchain_variant.tags + [ "kernel-with-tests" ] -
                       [ "kernel-with-tests" ] != toolchain_variant.tags
