# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("//build/bazel/rules/rust:defs.bzl", "rustc_library")

package(default_applicable_licenses = ["//:license"])

rustc_library(
    name = "async-generator",
    srcs = ["src/lib.rs"],
    crate_name = "async_generator",
    edition = "2024",
    lint_config = "//build/config/rust/lints:clippy_warn_all",
    visibility = [
        "//src/connectivity/policy/http-client:__subpackages__",
        "//src/sys/pkg:__subpackages__",
    ],
    with_unit_tests = True,
    deps = [
        "//third_party/rust_crates/vendor:futures",
        "//third_party/rust_crates/vendor:pin-project",
    ],
)
