# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("//build/bazel/rules/rust:defs.bzl", "rustc_library")

package(default_applicable_licenses = ["//:license"])

rustc_library(
    name = "types",
    srcs = [
        "src/lib.rs",
        "src/serde_ext.rs",
    ],
    # Some host tools use serde to serialize/deserialize severity.
    crate_features = select({
        "@platforms//os:fuchsia": [],
        "//conditions:default": ["serde"],
    }),
    crate_name = "diagnostics_log_types",
    edition = "2024",
    lint_config = "//build/config/rust/lints:clippy_warn_all",
    visibility = ["//visibility:public"],
    with_host_unit_tests = True,
    deps = [
        "//sdk/fidl/fuchsia.diagnostics.types:fuchsia.diagnostics.types_rust",
        "//third_party/rust_crates/vendor:log",
        "//third_party/rust_crates/vendor:thiserror",
    ] + select({
        "@platforms//os:fuchsia": [],
        "//conditions:default": [
            "//third_party/rust_crates/vendor:schemars",
            "//third_party/rust_crates/vendor:serde",
        ],
    }),
)

# Provided for users who need to use serde in the target.
rustc_library(
    name = "types-serde",
    srcs = [
        "src/serde_ext.rs",
        "src/serde_lib.rs",
    ],
    crate_name = "diagnostics_log_types_serde",
    crate_root = "src/serde_lib.rs",
    edition = "2024",
    lint_config = "//build/config/rust/lints:clippy_warn_all",
    visibility = ["//visibility:public"],
    with_host_unit_tests = True,
    deps = [
        ":types",
        "//third_party/rust_crates/vendor:serde",
    ],
)
