# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("//build/bazel/rules/rust:defs.bzl", "rustc_library")

package(
    default_applicable_licenses = ["//:license"],
    default_visibility = ["//visibility:public"],
)

rustc_library(
    name = "trace",
    srcs = ["src/lib.rs"],
    crate_name = "fuchsia_trace",
    edition = "2024",
    with_unit_tests = True,
    deps = [
        "//sdk/rust/zx",
        "//src/lib/fuchsia-runtime",
        "//third_party/rust_crates/vendor:libc",
        "//third_party/rust_crates/vendor:pin-project",
        "//third_party/rust_crates/vendor:rand",
        "//zircon/system/ulib/trace-engine",
    ],
)
