# Copyright 2019 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# End to end (E2E) product test runtime dependencies. This bundle can be added
# to a build spec that also contains end to end product tests, so they can be
# executed against an instance of the product.
group("end_to_end_deps") {
  testonly = true
  public_deps = [
    # Needed to send fake input.
    "//src/ui/tools:input",

    # SL4F to translate JSON-RPC to calls.
    "//src/testing/sl4f",

    # Needed for performance testing.
    "//src/performance/trace",

    # Needed for VP9 decode conformance testing.
    "//src/media/codec/examples:vp9_decoder_conformance_http",
  ]
}
