# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("//build/bazel/rules/rust:defs.bzl", "rustc_library")

package(default_applicable_licenses = ["//:license"])

rustc_library(
    name = "starnix_stack",
    srcs = ["src/lib.rs"],
    crate_name = "starnix_stack",
    edition = "2024",
    test_deps = ["//src/lib/fuchsia"],
    visibility = ["//src/starnix/kernel/core:__pkg__"],
    with_unit_tests = True,
    deps = [
        "//sdk/rust/zx",
        "//src/lib/fuchsia-runtime",
    ],
)
