# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

[package]
name = "sapphire-hci"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
sapphire-async = { path = "../sapphire-async" }
sapphire-sync = { path = "../sapphire-sync" }
sapphire-collections = { path = "../sapphire-collections" }
sapphire-rpc-macro = { path = "../sapphire-rpc-macro" }
thiserror = { version = "2.0.18", default-features = false }
futures = { version = "=0.3.31", default-features = false, features = ["async-await"] }
