# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# LINT.IfChange
declare_args() {
  # If true, use the newer vim3-dml driver instead of the vim3-devicetree
  # driver.
  use_vim3_dml = false
}
# LINT.ThenChange(//build/bazel/BUILD.gn)
