# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/components.gni")
import("//build/rust/rustc_test.gni")
import("//src/starnix/build/starnix_linux_rustc_binary.gni")
import("//src/starnix/tests/remotevol/remotevol_tests.gni")

group("tests") {
  testonly = true
  deps = [ ":starnix_remotevol_rename_locked_file_integration_test" ]
}

starnix_linux_rustc_binary("create_encrypted_file_for_rename_bin") {
  testonly = true
  edition = "2024"
  source_root = "src/debian_programs/create_encrypted_file.rs"
  sources = [ source_root ]
  deps = [
    "//src/starnix/tests/remotevol:remotevol_linux_test_util",
    "//third_party/rust_crates:zerocopy",
  ]
}

fuchsia_component("create_encrypted_file") {
  testonly = true
  manifest = "meta/create_encrypted_file.cml"
  deps = [ ":create_encrypted_file_for_rename_bin" ]
}

starnix_linux_rustc_binary("rename_encrypted_file_bin") {
  testonly = true
  edition = "2024"
  source_root = "src/debian_programs/rename_encrypted_file.rs"
  sources = [ source_root ]
  deps = [ "//third_party/rust_crates:libc" ]
}

fuchsia_component("rename_encrypted_file") {
  testonly = true
  manifest = "meta/rename_encrypted_file.cml"
  deps = [ ":rename_encrypted_file_bin" ]
}

rustc_test("remotevol_rename_locked_file_integration_test_bin") {
  edition = "2024"
  source_root = "src/rename_locked_file_test.rs"
  sources = [ source_root ]
  deps = [
    "//sdk/fidl/fuchsia.component:fuchsia.component_rust",
    "//sdk/fidl/fuchsia.component.decl:fuchsia.component.decl_rust",
    "//src/lib/fuchsia",
    "//src/lib/fuchsia-component-test",
    "//src/starnix/tests/remotevol:remotevol_fuchsia_test_util",
    "//src/sys/lib/component-events",
    "//third_party/rust_crates:log",
  ]
}

fuchsia_test_component("remotevol_rename_locked_file_test") {
  manifest = "meta/remotevol_rename_locked_file_test.cml"
  check_includes = false
  deps = [ ":remotevol_rename_locked_file_integration_test_bin" ]
  test_type = "starnix"
}

remotevol_tests_group("starnix_remotevol_rename_locked_file_integration_test") {
  test_components = [ ":remotevol_rename_locked_file_test" ]
  kernel_base_manifest = "meta/kernel_with_container.base.cml"
  deps = [
    ":create_encrypted_file",
    ":rename_encrypted_file",
  ]
  subpackages = [
    "//src/starnix/kernel:starnix_kernel_package",
    "//src/storage/fxfs/test-fxfs:test-fxfs-package",
    "//src/starnix/containers/debian:debian_package",
  ]
  test_specs = {
    package_resolution_timeout_secs = 660
  }
}
