# Copyright 2026 The Fuchsia Authors
#
# Use of this source code is governed by a MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT

source_set("ksync") {
  sources = [ "bindings.cc" ]
  deps = [ "//zircon/kernel/lib/lockdep" ]
}

group("tests") {
  testonly = true
}

group("kernel-tests") {
  testonly = true
}

group("phys-tests") {
  testonly = true
}

group("boot_tests") {
  testonly = true
}
