# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

[package]
name = "sub-crate-binary"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "foo-binary"
path = "src/main.rs"

[dev-dependencies]
test-helpers = { version = "0.1.0", path = "../test-helpers" }
