# Copyright 2023 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("../libc.gni")

llvm_libc_source_set("math") {
  noncpu_dir = "generic"

  # TODO(https://fxbug.dev/42141211): expanding this set piecemeal to ensure
  # performance of each function does not regress
  functions = [
    "fabs",
    "fabsf",
    "ldexp",
    "ldexpf",
    "ldexpl",
    "scalbln",
    "scalblnf",
    "scalblnl",
    "scalbn",
    "scalbnf",
    "scalbnl",
    "sqrt",
    "sqrtf",
  ]

  # The llvm-libc math tests require gtest and MPFR.
  no_test_functions = functions
}
