# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("@platforms//host:constraints.bzl", "HOST_CONSTRAINTS")
load("//build/bazel/rules/rust:defs.bzl", "rustc_library", "rustc_proc_macro")

package(default_applicable_licenses = ["//:license"])

rustc_library(
    name = "transformer",
    srcs = ["src/transformer.rs"],
    crate_name = "transformer",
    crate_root = "src/transformer.rs",
    edition = "2024",
    target_compatible_with = HOST_CONSTRAINTS,
    deps = [
        "//sdk/fidl/fuchsia.diagnostics.types:fuchsia.diagnostics.types_rust",
        "//third_party/rust_crates/vendor:proc-macro2",
        "//third_party/rust_crates/vendor:quote",
        "//third_party/rust_crates/vendor:syn",
    ],
)

rustc_proc_macro(
    name = "macro",
    srcs = ["src/lib.rs"],
    crate_name = "fuchsia_macro",
    edition = "2024",
    visibility = ["//src/lib/fuchsia:__pkg__"],
    deps = [":transformer"],
)
