# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("@platforms//host:constraints.bzl", "HOST_CONSTRAINTS")
load("//build/bazel/rules/rust:defs.bzl", "rustc_library")

package(default_applicable_licenses = ["//:license"])

rustc_library(
    name = "lib",
    srcs = [
        "src/enumerations.rs",
        "src/fletcher64.rs",
        "src/instances.rs",
        "src/lib.rs",
        "src/targets.rs",
    ],
    crate_name = "emulator_instance",
    edition = "2024",
    target_compatible_with = HOST_CONSTRAINTS,
    test_deps = [
        "//src/lib/fuchsia",
        "//third_party/rust_crates/vendor:tempfile",
    ],
    version = "0.1.0",
    visibility = ["//src/developer/ffx:__subpackages__"],
    with_host_unit_tests = True,
    deps = [
        "//build/sdk/meta:rust",
        "//sdk/fidl/fuchsia.net:fuchsia.net_rust",
        "//src/developer/ffx/fidl:fuchsia.developer.ffx_rust",
        "//third_party/rust_crates/vendor:anyhow",
        "//third_party/rust_crates/vendor:byteorder",
        "//third_party/rust_crates/vendor:futures",
        "//third_party/rust_crates/vendor:log",
        "//third_party/rust_crates/vendor:nix",
        "//third_party/rust_crates/vendor:notify",
        "//third_party/rust_crates/vendor:schemars",
        "//third_party/rust_crates/vendor:serde",
        "//third_party/rust_crates/vendor:serde_json",
        "//third_party/rust_crates/vendor:thiserror",
    ],
)
