# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("//build/bazel/rules/rust:defs.bzl", "rustc_library")

package(
    default_applicable_licenses = ["//:license"],
    default_visibility = ["//visibility:public"],
)

rustc_library(
    name = "fuchsia-emulated-handle",
    srcs = [
        "src/channel.rs",
        "src/lib.rs",
        "src/socket.rs",
    ],
    edition = "2024",
    test_deps = [
        "//third_party/rust_crates/vendor:futures-test",
    ],
    version = "0.1.0",
    with_host_unit_tests = True,
    deps = [
        "//sdk/rust/zx-status",
        "//sdk/rust/zx-status-ext",
        "//sdk/rust/zx-types",
        "//src/lib/fuchsia-sync",
        "//third_party/rust_crates/vendor:bitflags",
        "//third_party/rust_crates/vendor:futures",
        "//third_party/rust_crates/vendor:tokio",
    ],
)
