# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("//build/bazel/rules/rust:defs.bzl", "rustc_library")

package(default_applicable_licenses = ["//:license"])

rustc_library(
    name = "fuchsia-async-inspect",
    srcs = ["src/lib.rs"],
    edition = "2024",
    target_compatible_with = ["@platforms//os:fuchsia"],
    test_deps = [
        "//src/lib/diagnostics/testing/diagnostics-assertions/rust:diagnostics-assertions",
        "//src/lib/fuchsia",
        "//third_party/rust_crates/vendor:futures",
    ],
    visibility = ["//:__subpackages__"],
    with_unit_tests = True,
    deps = [
        "//sdk/rust/zx",
        "//src/lib/diagnostics/inspect/rust:fuchsia-inspect",
        "//src/lib/fuchsia-async",
        "//src/lib/fuchsia-sync",
    ],
)
