# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/rust/rustc_bindgen.gni")
import("//build/rust/rustc_library.gni")

rustc_bindgen("magma_common_defs_bindgen") {
  visibility = [ ":*" ]
  headers = [ "//sdk/lib/magma_common/include/lib/magma/magma_common_defs.h" ]
  output_name = "magma_common_defs.rs"

  layout_tests = false
  explicit_padding = false
  use_core = true

  raw_lines = [
    "pub const MAX_INFLIGHT_MESSAGES: u64 = 1000;",
    "pub const MAX_INFLIGHT_MEMORY_MB: u64 = 100;",
    "pub const MAX_INFLIGHT_BYTES: u64 = MAX_INFLIGHT_MEMORY_MB * 1024 * 1024;",
  ]

  replacements = [
    [
      "pub const MAGMA_STATUS_([A-Z0-9_]+): u32 =",
      "pub const MAGMA_STATUS_\\1: i32 =",
    ],
    [
      "pub const MAGMA_QUERY_([A-Z0-9_]+): u32 =",
      "pub const MAGMA_QUERY_\\1: u64 =",
    ],
    [
      "pub const MAGMA_MAP_FLAG_([A-Z0-9_]+): u32 =",
      "pub const MAGMA_MAP_FLAG_\\1: u64 =",
    ],
    [
      "pub const MAGMA_IMPORT_SEMAPHORE_ONE_SHOT: u32 =",
      "pub const MAGMA_IMPORT_SEMAPHORE_ONE_SHOT: u64 =",
    ],
  ]

  var_allowlist = [ "MAGMA_.*" ]
  type_allowlist = [ "magma_.*" ]

  include_dirs = [ "//sdk/lib/magma_common/include" ]

  additional_bindgen_flags = [ "--clang-macro-fallback" ]
  fuchsia_api_level = "HEAD"

  notice_year = 2026
}

rustc_library("magma-common-defs") {
  name = "magma_common_defs"
  edition = "2024"
  source_root = "$target_gen_dir/magma_common_defs.rs"
  sources = [ "$target_gen_dir/magma_common_defs.rs" ]
  deps = [ ":magma_common_defs_bindgen" ]
  rustflags = [
    "-A",
    "non_camel_case_types",
    "-A",
    "non_upper_case_globals",
  ]
}
